/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: sUj6qNzu2DyGvGvfQpYywu
// Component: VUJicClRyhQw
import * as React from "react";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import {
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  generateOnMutateForSpec,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  hasVariant,
  initializeCodeComponentStates,
  useDollarState
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import { NavigationBar } from "@plasmicpkgs/plasmic-nav";
import { FormWrapper } from "@plasmicpkgs/antd5/skinny/Form";
import { formHelpers as FormWrapper_Helpers } from "@plasmicpkgs/antd5/skinny/Form";
import { FormItemWrapper } from "@plasmicpkgs/antd5/skinny/FormItem";
import { AntdInput } from "@plasmicpkgs/antd5/skinny/registerInput";
import { inputHelpers as AntdInput_Helpers } from "@plasmicpkgs/antd5/skinny/registerInput";
import { AntdButton } from "@plasmicpkgs/antd5/skinny/registerButton";
import { Embed } from "@plasmicpkgs/plasmic-basic-components";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: sUj6qNzu2DyGvGvfQpYywu/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: sUj6qNzu2DyGvGvfQpYywu/styleTokensProvider
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: sUj6qNzu2DyGvGvfQpYywu/projectcss
import sty from "./PlasmicAboutUs.module.css"; // plasmic-import: VUJicClRyhQw/css

const emptyProxy = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q) {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export function generateDynamicMetadata($q, $ctx) {
  return {
    openGraph: {},
    twitter: {
      card: "summary"
    }
  };
}

createPlasmicElementProxy;

export const PlasmicAboutUs__VariantProps = new Array();

export const PlasmicAboutUs__ArgProps = new Array();

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicAboutUs__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const globalVariants = _useGlobalVariants();
  const stateSpecs = React.useMemo(
    () => [
      {
        path: "form.value",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined,
        refName: "form",
        onMutate: generateOnMutateForSpec("value", FormWrapper_Helpers)
      },
      {
        path: "form.isSubmitting",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => false,
        refName: "form",
        onMutate: generateOnMutateForSpec("isSubmitting", FormWrapper_Helpers)
      },
      {
        path: "input.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined,
        onMutate: generateOnMutateForSpec("value", AntdInput_Helpers)
      }
    ],

    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });
  const pageMetadata = generateDynamicMetadata(
    wrapQueriesWithLoadingProxy({}),
    $ctx
  );
  const styleTokensClassNames = _useStyleTokens();
  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"aboutUs"}
          data-plasmic-override={overrides.aboutUs}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.aboutUs
          )}
        >
          <div
            data-plasmic-name={"nav"}
            data-plasmic-override={overrides.nav}
            className={classNames(projectcss.all, sty.nav)}
            data-anim={"true"}
            data-anim-props={``}
            data-anim-type={"fromTo"}
          >
            <NavigationBar
              data-plasmic-name={"navBar"}
              data-plasmic-override={overrides.navBar}
              brand={
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    sty.link__ztUyh
                  )}
                  component={Link}
                  href={"#"}
                  legacyBehavior={false}
                  platform={"nextjs"}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__ihZLj)}
                    displayHeight={"74px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={
                      hasVariant(globalVariants, "screen", "mobile")
                        ? "100%"
                        : "156px"
                    }
                    src={{
                      src: "/plasmic/tosin_umoren/images/image.png",
                      fullWidth: 313,
                      fullHeight: 149,
                      aspectRatio: undefined
                    }}
                  />
                </PlasmicLink__>
              }
              className={classNames("__wab_instance", sty.navBar)}
              closeButton={
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__o1JYa)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  src={"https://static1.plasmic.app/close.svg"}
                />
              }
              itemsGap={8}
              menuItems={
                <React.Fragment>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__zxKKr
                    )}
                    component={Link}
                    href={"/"}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"Home"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__nFlvV
                    )}
                    component={Link}
                    href={`/about-us`}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"About us"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link___9JzzE
                    )}
                    component={Link}
                    href={"/#Wdo"}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"What We Do"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__hQijS
                    )}
                    component={Link}
                    href={`/gallery`}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"Media"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__uoQS
                    )}
                    component={Link}
                    href={`/contact-us`}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"Contact"}
                  </PlasmicLink__>
                </React.Fragment>
              }
              openButton={
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__x1Bz7)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  height={
                    hasVariant(globalVariants, "screen", "tablet")
                      ? "50%"
                      : undefined
                  }
                  src={"https://static1.plasmic.app/menu.svg"}
                  width={
                    hasVariant(globalVariants, "screen", "tablet")
                      ? "50%"
                      : undefined
                  }
                />
              }
              responsiveBreakpoint={768}
            />

            <PlasmicLink__
              data-plasmic-name={"heroBtn3"}
              data-plasmic-override={overrides.heroBtn3}
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.__wab_text,
                sty.heroBtn3
              )}
              component={Link}
              href={`/donation`}
              legacyBehavior={false}
              platform={"nextjs"}
            >
              {"Donate"}
            </PlasmicLink__>
          </div>
          <div
            data-plasmic-name={"wrapper"}
            data-plasmic-override={overrides.wrapper}
            className={classNames(projectcss.all, sty.wrapper)}
          >
            <div
              className={classNames(projectcss.all, sty.freeBox__s9G0B)}
              data-anim={"true"}
              data-anim-props={
                '{\n\n           "from": {"autoAlpha":0,\n"x": -100},\n\n           "to": {"autoAlpha":1,\n"x": 0},\n\n           "duration": 0.8\n\n         }'
              }
              data-anim-type={"fromTo"}
            >
              <div className={classNames(projectcss.all, sty.freeBox__frhMk)} />
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__pUpU2
                )}
              >
                {"Brief History & Purpose"}
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__hcYdN)}>
              <div
                data-plasmic-name={"innerContents2"}
                data-plasmic-override={overrides.innerContents2}
                className={classNames(projectcss.all, sty.innerContents2)}
              >
                <h1
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.__wab_text,
                    sty.h1__rtFYd
                  )}
                  data-anim={"true"}
                  data-anim-props={
                    '{\n\n           "from": {"autoAlpha":0,\n"x": -100},\n\n           "to": {"autoAlpha":1,\n"x": 0},\n\n           "duration": 0.8\n\n         }'
                  }
                  data-anim-type={"fromTo"}
                >
                  {"ABOUT THE FOUNDATION"}
                </h1>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__enKgx
                  )}
                  data-anim={"true"}
                  data-anim-props={
                    '{\n\n           "from": {"autoAlpha":0,\n"x": 100},\n\n           "to": {"autoAlpha":1,\n"x": 0},\n\n           "duration": 0.8\n\n         }'
                  }
                  data-anim-type={"fromTo"}
                >
                  {
                    "Founded by Oluwatosin Umoren, Tosin Umoren Foundation was born from a deep personal conviction and lived experiences. What started as a calling has grown into a structured platform committed to ensuring that no child or elderly person is neglected.\n\nThe foundation exists not just to provide temporary relief, but to create long-term transformation, by rewiring mindsets, empowering families, and restoring dignity."
                  }
                </div>
              </div>
              <div
                data-plasmic-name={"innerContents3"}
                data-plasmic-override={overrides.innerContents3}
                className={classNames(projectcss.all, sty.innerContents3)}
                data-anim={"true"}
                data-anim-props={
                  '{\n\n           "from": {"autoAlpha":1,\n"scale": 1.05},\n\n           "to": {"autoAlpha":1,\n"scale": 1},\n\n           "duration": 0.8\n\n         }'
                }
                data-anim-type={"fromTo"}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__miuUe)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={
                    hasVariant(globalVariants, "screen", "tablet")
                      ? "20%"
                      : "5%"
                  }
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/tosin_umoren/images/image27.png",
                    fullWidth: 128,
                    fullHeight: 127,
                    aspectRatio: undefined
                  }}
                />
              </div>
            </div>
          </div>
          <section
            data-plasmic-name={"statements"}
            data-plasmic-override={overrides.statements}
            className={classNames(projectcss.all, sty.statements, "v-scroll")}
          >
            <div
              className={classNames(projectcss.all, sty.columns__xa8WG)}
              data-anim={"true"}
              data-anim-props={
                hasVariant(globalVariants, "screen", "mobile")
                  ? ``
                  : '{\n\n"scrollTrigger": {\n\n"trigger": ".v-scroll",\n\n"start": "top 80%",\n\n"end": "bottom 20%",\n\n"scrub": true,\n\n"toggleActions": "play none none reverse"\n\n},\n\n"y": -100,\n\n"opacity": 0,\n\n"duration": 1.5,\n\n"stagger": 0.5,\n\n"ease": "power4.out"\n\n}'
              }
              data-anim-type={"from"}
            >
              <div className={classNames(projectcss.all, sty.column__lvKAw)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__yDaFv
                  )}
                >
                  {"Vision Statement"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__gjJ3Z
                  )}
                >
                  {
                    "To create a world where no child or elderly person is forgotten, and where mindsets are rewired to break generational limitations."
                  }
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__sqTzN)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__mmIoc
                  )}
                >
                  {"Mission Statement"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__vmwQg
                  )}
                >
                  {
                    "To restore hope and dignity to underserved children and elderly individuals through education support, healthcare assistance, food outreach, and mindset transformation, empowering families to rise beyond their circumstances. "
                  }
                </div>
              </div>
            </div>
          </section>
          <section
            data-plasmic-name={"foundersMessage"}
            data-plasmic-override={overrides.foundersMessage}
            className={classNames(
              projectcss.all,
              sty.foundersMessage,
              "m-scroll"
            )}
          >
            <div
              data-plasmic-name={"ourFounder"}
              data-plasmic-override={overrides.ourFounder}
              className={classNames(projectcss.all, sty.ourFounder)}
              data-anim={"true"}
              data-anim-props={
                '{\n\n"scrollTrigger": {\n\n"trigger": ".m-scroll",\n\n"start": "top 80%",\n\n"end": "bottom 20%",\n\n"scrub": true,\n\n"toggleActions": "play none none reverse"\n\n},\n\n"y": -100,\n\n"opacity": 0,\n\n"duration": 1.5,\n\n"stagger": 0.5,\n\n"ease": "power4.out"\n\n}'
              }
              data-anim-type={"from"}
            >
              <div
                data-plasmic-name={"contentsAbout2"}
                data-plasmic-override={overrides.contentsAbout2}
                className={classNames(projectcss.all, sty.contentsAbout2)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__ezihy)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox___24IjX)}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ppmaZ
                    )}
                  >
                    {"Founder\u2019s Message "}
                  </div>
                </div>
                <div
                  data-plasmic-name={"innerContents4"}
                  data-plasmic-override={overrides.innerContents4}
                  className={classNames(projectcss.all, sty.innerContents4)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__mpjod
                    )}
                  >
                    {
                      "Tosin Umoren Foundation is more than an organization to me, it is a calling. It was born from my personal journey and the strong conviction that no one should be abandoned because of their circumstances. \n\nEvery outreach, every hospital bill paid, every food item shared, and every smile restored reminds me why we started. We are not just giving help, we are giving hope, dignity, and a reason to keep living.\n\nThank you for believing in this vision."
                    }
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___8L6Uw
                    )}
                  >
                    {"Oluwatosin Umoren"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__uc31N
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontStyle: "italic", fontWeight: 700 }}
                      >
                        {"Founder/ Executive Director"}
                      </span>
                    </React.Fragment>
                  </div>
                </div>
              </div>
              <div
                data-plasmic-name={"imageAbout2"}
                data-plasmic-override={overrides.imageAbout2}
                className={classNames(projectcss.all, sty.imageAbout2)}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__lxKpm)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={
                    hasVariant(globalVariants, "screen", "tablet")
                      ? "100%"
                      : "80%"
                  }
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/tosin_umoren/images/image28.png",
                    fullWidth: 938,
                    fullHeight: 1088,
                    aspectRatio: undefined
                  }}
                />
              </div>
            </div>
          </section>
          <section
            data-plasmic-name={"values"}
            data-plasmic-override={overrides.values}
            className={classNames(projectcss.all, sty.values, "c-scroll")}
          >
            <h1
              className={classNames(
                projectcss.all,
                projectcss.h1,
                projectcss.__wab_text,
                sty.h1___11Pjb
              )}
              data-anim={"true"}
              data-anim-props={
                '{\n\n"scrollTrigger": {\n\n"trigger": ".c-scroll",\n\n"start": "top 80%",\n\n"end": "bottom 20%",\n\n"scrub": true,\n\n"toggleActions": "play none none reverse"\n\n},\n\n"y": -100,\n\n"opacity": 0,\n\n"duration": 1.5,\n\n"stagger": 0.5,\n\n"ease": "power4.out"\n\n}'
              }
              data-anim-type={"from"}
            >
              {"Core Values"}
            </h1>
            <div
              className={classNames(projectcss.all, sty.columns__gb6M)}
              data-anim={"true"}
              data-anim-props={
                '{\n\n"scrollTrigger": {\n\n"trigger": ".c-scroll",\n\n"start": "top 80%",\n\n"end": "bottom 20%",\n\n"scrub": true,\n\n"toggleActions": "play none none reverse"\n\n},\n\n"y": -100,\n\n"opacity": 0,\n\n"duration": 1.5,\n\n"stagger": 0.5,\n\n"ease": "power4.out"\n\n}'
              }
              data-anim-type={"from"}
            >
              <div className={classNames(projectcss.all, sty.column__tb8Xc)}>
                <div className={classNames(projectcss.all, sty.freeBox__nxP4V)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___1SuWv
                    )}
                  >
                    {"Compassion"}
                  </div>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__aOMxf)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={
                      hasVariant(globalVariants, "screen", "mobile")
                        ? "10%"
                        : hasVariant(globalVariants, "screen", "tablet")
                          ? "5%"
                          : "10%"
                    }
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/tosin_umoren/images/image29.png",
                      fullWidth: 56,
                      fullHeight: 56,
                      aspectRatio: undefined
                    }}
                  />
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__flRCi
                  )}
                >
                  {
                    "We serve with empathy, kindness, and a genuine concern for every life we touch."
                  }
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__iGErL)}>
                <div className={classNames(projectcss.all, sty.freeBox__ftlhB)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__jiGc
                    )}
                  >
                    {"Integrity"}
                  </div>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__h4NzR)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={
                      hasVariant(globalVariants, "screen", "mobile")
                        ? "10%"
                        : hasVariant(globalVariants, "screen", "tablet")
                          ? "5%"
                          : "10%"
                    }
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/tosin_umoren/images/image29.png",
                      fullWidth: 56,
                      fullHeight: 56,
                      aspectRatio: undefined
                    }}
                  />
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___2FHpb
                  )}
                >
                  {
                    "We act honestly, ethically, and transparently in all that we do."
                  }
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__vSw4E)}>
                <div
                  className={classNames(projectcss.all, sty.freeBox___6SKtc)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__cTrfi
                    )}
                  >
                    {"Excellence"}
                  </div>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__sj7Zf)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={
                      hasVariant(globalVariants, "screen", "mobile")
                        ? "10%"
                        : hasVariant(globalVariants, "screen", "tablet")
                          ? "5%"
                          : "10%"
                    }
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/tosin_umoren/images/image29.png",
                      fullWidth: 56,
                      fullHeight: 56,
                      aspectRatio: undefined
                    }}
                  />
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__klxF
                  )}
                >
                  {
                    "We are committed to delivering impactful services with the highest standards."
                  }
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__wiBAu)}>
                <div
                  className={classNames(projectcss.all, sty.freeBox___2B86O)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__uPxn4
                    )}
                  >
                    {"Dignity"}
                  </div>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__b07JD)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={
                      hasVariant(globalVariants, "screen", "mobile")
                        ? "10%"
                        : hasVariant(globalVariants, "screen", "tablet")
                          ? "5%"
                          : "10%"
                    }
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/tosin_umoren/images/image29.png",
                      fullWidth: 56,
                      fullHeight: 56,
                      aspectRatio: undefined
                    }}
                  />
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__obP6Q
                  )}
                >
                  {
                    "We respect and uphold the worth of every individual, without discrimination."
                  }
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__rcOFr)}>
                <div
                  className={classNames(projectcss.all, sty.freeBox___7Nulx)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__sxQbF
                    )}
                  >
                    {"Community"}
                  </div>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__voAlq)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={
                      hasVariant(globalVariants, "screen", "mobile")
                        ? "10%"
                        : hasVariant(globalVariants, "screen", "tablet")
                          ? "5%"
                          : "10%"
                    }
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/tosin_umoren/images/image29.png",
                      fullWidth: 56,
                      fullHeight: 56,
                      aspectRatio: undefined
                    }}
                  />
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ww6G9
                  )}
                >
                  {
                    "We believe in the power of unity and collective action to create lasting change"
                  }
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__lo5Xn)}>
                <div className={classNames(projectcss.all, sty.freeBox__sSgc5)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__cm45M
                    )}
                  >
                    {"Accountability"}
                  </div>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img___2R0Sx)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={
                      hasVariant(globalVariants, "screen", "mobile")
                        ? "10%"
                        : hasVariant(globalVariants, "screen", "tablet")
                          ? "5%"
                          : "10%"
                    }
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/tosin_umoren/images/image29.png",
                      fullWidth: 56,
                      fullHeight: 56,
                      aspectRatio: undefined
                    }}
                  />
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__elO4T
                  )}
                >
                  {
                    "We take responsibility for our actions and steward every resource with care."
                  }
                </div>
              </div>
            </div>
          </section>
          <section
            data-plasmic-name={"pageWrapper2"}
            data-plasmic-override={overrides.pageWrapper2}
            className={classNames(projectcss.all, sty.pageWrapper2, "t-scroll")}
          >
            <div
              data-plasmic-name={"aboutUs2"}
              data-plasmic-override={overrides.aboutUs2}
              className={classNames(projectcss.all, sty.aboutUs2)}
            >
              <div
                data-plasmic-name={"contentsAbout3"}
                data-plasmic-override={overrides.contentsAbout3}
                className={classNames(projectcss.all, sty.contentsAbout3)}
                data-anim={"true"}
                data-anim-props={
                  hasVariant(globalVariants, "screen", "mobile")
                    ? ``
                    : '{\n\n"scrollTrigger": {\n\n"trigger": ".t-scroll",\n\n"start": "top 80%",\n\n"end": "bottom 20%",\n\n"scrub": true,\n\n"toggleActions": "play none none reverse"\n\n},\n\n"y": -100,\n\n"opacity": 0,\n\n"duration": 1.5,\n\n"stagger": 0.5,\n\n"ease": "power4.out"\n\n}'
                }
                data-anim-type={"from"}
              >
                <div className={classNames(projectcss.all, sty.freeBox__eipkx)}>
                  <h1
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1__tRMnH
                    )}
                  >
                    {"Meet our team"}
                  </h1>
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___7Hszq
                  )}
                >
                  {"A passionate team united by purpose and compassion."}
                </div>
              </div>
            </div>
            <div
              className={classNames(projectcss.all, sty.columns__uqCu)}
              data-anim={"true"}
              data-anim-props={
                hasVariant(globalVariants, "screen", "mobile")
                  ? ``
                  : '{\n\n"scrollTrigger": {\n\n"trigger": ".t-scroll",\n\n"start": "top 80%",\n\n"end": "bottom 20%",\n\n"scrub": true,\n\n"toggleActions": "play none none reverse"\n\n},\n\n"y": -100,\n\n"opacity": 0,\n\n"duration": 1.5,\n\n"stagger": 0.5,\n\n"ease": "power4.out"\n\n}'
              }
              data-anim-type={"from"}
            >
              <div className={classNames(projectcss.all, sty.column__piQyz)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__mfWm0)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/tosin_umoren/images/imagePng.png",
                    fullWidth: 888,
                    fullHeight: 960,
                    aspectRatio: undefined
                  }}
                />

                <div className={classNames(projectcss.all, sty.freeBox__fwdfm)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ftbyh
                    )}
                  >
                    {"Leonard John Davies"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__c5EX
                    )}
                  >
                    {"Cofounder, CEO"}
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__vF0W)}
                  >
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__uqbGn
                      )}
                      component={Link}
                      legacyBehavior={false}
                      platform={"nextjs"}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__iSkmX)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={
                          hasVariant(globalVariants, "screen", "tablet")
                            ? "80%"
                            : "80%"
                        }
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/tosin_umoren/images/image30.png",
                          fullWidth: 40,
                          fullHeight: 40,
                          aspectRatio: undefined
                        }}
                      />
                    </PlasmicLink__>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__lw2O
                      )}
                      component={Link}
                      legacyBehavior={false}
                      platform={"nextjs"}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__te9WH)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={
                          hasVariant(globalVariants, "screen", "tablet")
                            ? "80%"
                            : "80%"
                        }
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/tosin_umoren/images/image31.png",
                          fullWidth: 40,
                          fullHeight: 40,
                          aspectRatio: undefined
                        }}
                      />
                    </PlasmicLink__>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__mhcUb
                      )}
                      component={Link}
                      legacyBehavior={false}
                      platform={"nextjs"}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img___2Jqbn)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={
                          hasVariant(globalVariants, "screen", "tablet")
                            ? "80%"
                            : "80%"
                        }
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/tosin_umoren/images/image32.png",
                          fullWidth: 40,
                          fullHeight: 40,
                          aspectRatio: undefined
                        }}
                      />
                    </PlasmicLink__>
                  </div>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column___7UJar)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__n681)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/tosin_umoren/images/image2Png.png",
                    fullWidth: 888,
                    fullHeight: 960,
                    aspectRatio: undefined
                  }}
                />

                <div className={classNames(projectcss.all, sty.freeBox__zMnMe)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__cic5O
                    )}
                  >
                    {"Francis Weber"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___8CboB
                    )}
                  >
                    {"Vice Chairman"}
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox___4P1Iw)}
                  >
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__iJIyc
                      )}
                      component={Link}
                      legacyBehavior={false}
                      platform={"nextjs"}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__yjOdW)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={
                          hasVariant(globalVariants, "screen", "tablet")
                            ? "80%"
                            : "80%"
                        }
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/tosin_umoren/images/image30.png",
                          fullWidth: 40,
                          fullHeight: 40,
                          aspectRatio: undefined
                        }}
                      />
                    </PlasmicLink__>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link___0YoVm
                      )}
                      component={Link}
                      legacyBehavior={false}
                      platform={"nextjs"}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__n90Gc)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={
                          hasVariant(globalVariants, "screen", "tablet")
                            ? "80%"
                            : "80%"
                        }
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/tosin_umoren/images/image31.png",
                          fullWidth: 40,
                          fullHeight: 40,
                          aspectRatio: undefined
                        }}
                      />
                    </PlasmicLink__>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link___9N9Rn
                      )}
                      component={Link}
                      legacyBehavior={false}
                      platform={"nextjs"}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__xW4B)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={
                          hasVariant(globalVariants, "screen", "tablet")
                            ? "80%"
                            : "80%"
                        }
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/tosin_umoren/images/image32.png",
                          fullWidth: 40,
                          fullHeight: 40,
                          aspectRatio: undefined
                        }}
                      />
                    </PlasmicLink__>
                  </div>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__ztgnE)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__tyIcv)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/tosin_umoren/images/image1Png.png",
                    fullWidth: 888,
                    fullHeight: 960,
                    aspectRatio: undefined
                  }}
                />

                <div
                  className={classNames(projectcss.all, sty.freeBox___443Pq)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__furJ
                    )}
                  >
                    {"Kyla Obrien"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___5EihO
                    )}
                  >
                    {"Head of Authority"}
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox___7X9Of)}
                  >
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__kvQw
                      )}
                      component={Link}
                      legacyBehavior={false}
                      platform={"nextjs"}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__lMl0D)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={
                          hasVariant(globalVariants, "screen", "tablet")
                            ? "80%"
                            : "80%"
                        }
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/tosin_umoren/images/image30.png",
                          fullWidth: 40,
                          fullHeight: 40,
                          aspectRatio: undefined
                        }}
                      />
                    </PlasmicLink__>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__aUiJw
                      )}
                      component={Link}
                      legacyBehavior={false}
                      platform={"nextjs"}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img___0E6Zz)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={
                          hasVariant(globalVariants, "screen", "tablet")
                            ? "80%"
                            : "80%"
                        }
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/tosin_umoren/images/image31.png",
                          fullWidth: 40,
                          fullHeight: 40,
                          aspectRatio: undefined
                        }}
                      />
                    </PlasmicLink__>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__t9Zdw
                      )}
                      component={Link}
                      legacyBehavior={false}
                      platform={"nextjs"}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__k9Bh5)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={
                          hasVariant(globalVariants, "screen", "tablet")
                            ? "80%"
                            : "80%"
                        }
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/tosin_umoren/images/image32.png",
                          fullWidth: 40,
                          fullHeight: 40,
                          aspectRatio: undefined
                        }}
                      />
                    </PlasmicLink__>
                  </div>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column___1MdjX)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__zYaf)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/tosin_umoren/images/image3Png.png",
                    fullWidth: 888,
                    fullHeight: 960,
                    aspectRatio: undefined
                  }}
                />

                <div className={classNames(projectcss.all, sty.freeBox__evbt7)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___0JmV7
                    )}
                  >
                    {"Adrian Dixon"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__kLqAa
                    )}
                  >
                    {"Support Executive"}
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__urtkw)}
                  >
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__ekkLe
                      )}
                      component={Link}
                      legacyBehavior={false}
                      platform={"nextjs"}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__rJbzc)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={
                          hasVariant(globalVariants, "screen", "tablet")
                            ? "80%"
                            : "80%"
                        }
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/tosin_umoren/images/image30.png",
                          fullWidth: 40,
                          fullHeight: 40,
                          aspectRatio: undefined
                        }}
                      />
                    </PlasmicLink__>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__k4T0H
                      )}
                      component={Link}
                      legacyBehavior={false}
                      platform={"nextjs"}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__yWyti)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={
                          hasVariant(globalVariants, "screen", "tablet")
                            ? "80%"
                            : "80%"
                        }
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/tosin_umoren/images/image31.png",
                          fullWidth: 40,
                          fullHeight: 40,
                          aspectRatio: undefined
                        }}
                      />
                    </PlasmicLink__>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link___0I7Jg
                      )}
                      component={Link}
                      legacyBehavior={false}
                      platform={"nextjs"}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__upD5Y)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={
                          hasVariant(globalVariants, "screen", "tablet")
                            ? "80%"
                            : "80%"
                        }
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/tosin_umoren/images/image32.png",
                          fullWidth: 40,
                          fullHeight: 40,
                          aspectRatio: undefined
                        }}
                      />
                    </PlasmicLink__>
                  </div>
                </div>
              </div>
            </div>
          </section>
          <div
            className={classNames(
              projectcss.all,
              sty.freeBox__s6EZw,
              "j-scroll"
            )}
          >
            <section
              data-plasmic-name={"joinCOmmunity"}
              data-plasmic-override={overrides.joinCOmmunity}
              className={classNames(projectcss.all, sty.joinCOmmunity, ``)}
              data-anim={"true"}
              data-anim-props={
                '{\n\n"scrollTrigger": {\n\n"trigger": ".j-scroll",\n\n"start": "top 80%",\n\n"end": "bottom 20%",\n\n"scrub": true,\n\n"toggleActions": "play none none reverse"\n\n},\n\n"scale": 1.09,\n\n"opacity": 1,\n\n"duration": 1.5,\n\n"stagger": 0.5,\n\n"ease": "power4.out"\n\n}'
              }
              data-anim-type={"from"}
            >
              <h1
                className={classNames(
                  projectcss.all,
                  projectcss.h1,
                  projectcss.__wab_text,
                  sty.h1__gtKik
                )}
              >
                {
                  "Support our mission. Donate today and help us reach more lives with compassion and purpose."
                }
              </h1>
              <PlasmicLink__
                data-plasmic-name={"heroBtn4"}
                data-plasmic-override={overrides.heroBtn4}
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  projectcss.__wab_text,
                  sty.heroBtn4
                )}
                component={Link}
                href={`/donation`}
                legacyBehavior={false}
                platform={"nextjs"}
              >
                {"Donate"}
              </PlasmicLink__>
            </section>
          </div>
          <div
            data-plasmic-name={"events"}
            data-plasmic-override={overrides.events}
            className={classNames(projectcss.all, sty.events, "E-scroll")}
          >
            <div
              className={classNames(projectcss.all, sty.freeBox__zzFrk)}
              data-anim={"true"}
              data-anim-props={``}
              data-anim-type={"from"}
            >
              <div className={classNames(projectcss.all, sty.freeBox__aOxSq)} />
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___2WGst
                )}
              >
                {"Our Events"}
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__eGYxm)}>
              <div
                className={classNames(projectcss.all, sty.columns__kzmbR)}
                data-anim={"true"}
                data-anim-props={
                  '{\n\n"scrollTrigger": {\n\n"trigger": ".E-scroll",\n\n"start": "top 80%",\n\n"end": "bottom 20%",\n\n"scrub": true,\n\n"toggleActions": "play none none reverse"\n\n},\n\n"y": -100,\n\n"opacity": 0,\n\n"duration": 1.5,\n\n"stagger": 0.5,\n\n"ease": "power4.out"\n\n}'
                }
                data-anim-type={"from"}
              >
                <div className={classNames(projectcss.all, sty.column__wayDi)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__yzWby)}
                  >
                    <h1
                      className={classNames(
                        projectcss.all,
                        projectcss.h1,
                        projectcss.__wab_text,
                        sty.h1___2UjNd
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{"7TH\n"}</React.Fragment>
                        {
                          <h4
                            className={classNames(
                              projectcss.all,
                              projectcss.h4,
                              projectcss.__wab_text,
                              sty.h4__pom95
                            )}
                          >
                            <React.Fragment>
                              <span
                                className={
                                  "plasmic_default__all plasmic_default__span"
                                }
                                style={{ fontWeight: 700 }}
                              >
                                {"MARCH"}
                              </span>
                            </React.Fragment>
                          </h4>
                        }
                        <React.Fragment>{""}</React.Fragment>
                      </React.Fragment>
                    </h1>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__aXjsH)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__xaVrX
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__j6Hkp
                          )}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__kQxto
                          )}
                        >
                          {"Next Events"}
                        </div>
                      </div>
                      <h1
                        className={classNames(
                          projectcss.all,
                          projectcss.h1,
                          projectcss.__wab_text,
                          sty.h1__hAswE
                        )}
                      >
                        {"Celebration of Mothers for Women\u2019s Day"}
                      </h1>
                    </div>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__jR7Ab
                      )}
                      component={Link}
                      legacyBehavior={false}
                      platform={"nextjs"}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img___2LpPs)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"80%"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/tosin_umoren/images/image23.png",
                          fullWidth: 112,
                          fullHeight: 112,
                          aspectRatio: undefined
                        }}
                      />
                    </PlasmicLink__>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.column__nbEzn)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__wt23O)}
                  >
                    <h1
                      className={classNames(
                        projectcss.all,
                        projectcss.h1,
                        projectcss.__wab_text,
                        sty.h1__yvHso
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{"27TH\n"}</React.Fragment>
                        {
                          <h4
                            className={classNames(
                              projectcss.all,
                              projectcss.h4,
                              projectcss.__wab_text,
                              sty.h4__nghRl
                            )}
                          >
                            <React.Fragment>
                              <span
                                className={
                                  "plasmic_default__all plasmic_default__span"
                                }
                                style={{ fontWeight: 700 }}
                              >
                                {"MAY"}
                              </span>
                            </React.Fragment>
                          </h4>
                        }
                        <React.Fragment>{""}</React.Fragment>
                      </React.Fragment>
                    </h1>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__e8Lks)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__jkkQj
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__jEo6J
                          )}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__yOrfJ
                          )}
                        >
                          {"Next Events"}
                        </div>
                      </div>
                      <h1
                        className={classNames(
                          projectcss.all,
                          projectcss.h1,
                          projectcss.__wab_text,
                          sty.h1__rqeMm
                        )}
                      >
                        {
                          "Children\u2019s Day celebration in collaboration with a media company."
                        }
                      </h1>
                    </div>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__zaElQ
                      )}
                      component={Link}
                      legacyBehavior={false}
                      platform={"nextjs"}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__hzNps)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"80%"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/tosin_umoren/images/image23.png",
                          fullWidth: 112,
                          fullHeight: 112,
                          aspectRatio: undefined
                        }}
                      />
                    </PlasmicLink__>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames(projectcss.all, sty.footer, "F-scroll")}
          >
            <div
              className={classNames(projectcss.all, sty.columns__mSzr)}
              data-anim={"true"}
              data-anim-props={
                '{\n\n"scrollTrigger": {\n\n"trigger": ".F-scroll",\n\n"start": "top 80%",\n\n"end": "bottom 20%",\n\n"scrub": true,\n\n"toggleActions": "play none none reverse"\n\n},\n\n"y": -100,\n\n"opacity": 0,\n\n"duration": 1.5,\n\n"stagger": 0.5,\n\n"ease": "power4.out"\n\n}'
              }
              data-anim-type={"from"}
            >
              <div className={classNames(projectcss.all, sty.column__le1Rf)}>
                <div className={classNames(projectcss.all, sty.freeBox__kN2Mz)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__rWkO)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/tosin_umoren/images/image.png",
                      fullWidth: 313,
                      fullHeight: 149,
                      aspectRatio: undefined
                    }}
                  />
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__leLiQ)}>
                <h1
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.__wab_text,
                    sty.h1__iLum
                  )}
                >
                  {"Contact Us"}
                </h1>
                <div className={classNames(projectcss.all, sty.freeBox__jvHly)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__tb5Nm
                    )}
                  >
                    {"EMAIL US:"}
                  </div>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__eHczQ
                    )}
                    component={Link}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"tosinumorenfoundation@gmail.com\r"}
                  </PlasmicLink__>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__r9NOg)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__eyq11
                    )}
                  >
                    {"PHONE:"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__pdm6G
                    )}
                  >
                    {"+234 813 072 2129, +1760 829 0816"}
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__toaKr)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__x3AVd
                    )}
                  >
                    {"LOCATION:"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__sCa2L
                    )}
                  >
                    {"Nigeria (Outreaches across Lagos, Oyo, Osun & Ekiti)"}
                  </div>
                </div>
                <div
                  className={classNames(projectcss.all, sty.freeBox___72L5I)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__kWcQ9
                    )}
                  >
                    {"SOCIALS:"}
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__mfItm)}
                  >
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link___7FZap
                      )}
                      component={Link}
                      legacyBehavior={false}
                      platform={"nextjs"}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img___5FLkK)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={
                          hasVariant(globalVariants, "screen", "mobile")
                            ? "80%"
                            : "auto"
                        }
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/tosin_umoren/images/image26.png",
                          fullWidth: 36,
                          fullHeight: 36,
                          aspectRatio: undefined
                        }}
                      />
                    </PlasmicLink__>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__r22BY
                      )}
                      component={Link}
                      legacyBehavior={false}
                      platform={"nextjs"}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__qiAur)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={
                          hasVariant(globalVariants, "screen", "mobile")
                            ? "80%"
                            : "auto"
                        }
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/tosin_umoren/images/image25.png",
                          fullWidth: 36,
                          fullHeight: 36,
                          aspectRatio: undefined
                        }}
                      />
                    </PlasmicLink__>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__n0OPq
                      )}
                      component={Link}
                      legacyBehavior={false}
                      platform={"nextjs"}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__txoCa)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={
                          hasVariant(globalVariants, "screen", "mobile")
                            ? "80%"
                            : "auto"
                        }
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/tosin_umoren/images/image24.png",
                          fullWidth: 36,
                          fullHeight: 36,
                          aspectRatio: undefined
                        }}
                      />
                    </PlasmicLink__>
                  </div>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__oxV4E)}>
                <h1
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.__wab_text,
                    sty.h1___0Xqaq
                  )}
                >
                  {"Links"}
                </h1>
                <div
                  className={classNames(projectcss.all, sty.freeBox___9YFwn)}
                >
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__sB6Mh
                    )}
                    component={Link}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"Projects"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__rI1Us
                    )}
                    component={Link}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"Events"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__iokEg
                    )}
                    component={Link}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"Donate"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__xa2Mz
                    )}
                    component={Link}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"News"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__uzlyM
                    )}
                    component={Link}
                    href={`/gallery`}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"Gallery"}
                  </PlasmicLink__>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column___9LmL)}>
                <h1
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.__wab_text,
                    sty.h1__rmAk7
                  )}
                >
                  {"Subscribe to get latest updates"}
                </h1>
                {(() => {
                  const child$Props = {
                    className: classNames("__wab_instance", sty.form),
                    extendedOnValuesChange: async (...eventArgs) => {
                      generateStateOnChangePropForCodeComponents(
                        $state,
                        "value",
                        ["form", "value"],
                        FormWrapper_Helpers
                      ).apply(null, eventArgs);
                    },
                    formItems: [
                      { label: "Name", name: "name", inputType: "Text" },
                      {
                        label: "Message",
                        name: "message",
                        inputType: "Text Area"
                      }
                    ],

                    labelCol: { span: 8, horizontalOnly: true },
                    layout: "vertical",
                    mode: "advanced",
                    onIsSubmittingChange: async (...eventArgs) => {
                      generateStateOnChangePropForCodeComponents(
                        $state,
                        "isSubmitting",
                        ["form", "isSubmitting"],
                        FormWrapper_Helpers
                      ).apply(null, eventArgs);
                    },
                    ref: ref => {
                      $refs["form"] = ref;
                    },
                    submitSlot: null,
                    wrapperCol: { span: 16, horizontalOnly: true }
                  };
                  initializeCodeComponentStates(
                    $state,
                    [
                      {
                        name: "value",
                        plasmicStateName: "form.value"
                      },
                      {
                        name: "isSubmitting",
                        plasmicStateName: "form.isSubmitting"
                      }
                    ],

                    [],
                    FormWrapper_Helpers ?? {},
                    child$Props
                  );
                  return (
                    <FormWrapper
                      data-plasmic-name={"form"}
                      data-plasmic-override={overrides.form}
                      {...child$Props}
                    >
                      <FormItemWrapper
                        data-plasmic-name={"formField"}
                        data-plasmic-override={overrides.formField}
                        className={classNames("__wab_instance", sty.formField)}
                        label={
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__ln650
                            )}
                          >
                            {"Your Email"}
                          </div>
                        }
                        name={"email"}
                      >
                        {(() => {
                          const child$Props = {
                            className: classNames("__wab_instance", sty.input),
                            onChange: async (...eventArgs) => {
                              generateStateOnChangePropForCodeComponents(
                                $state,
                                "value",
                                ["input", "value"],
                                AntdInput_Helpers
                              ).apply(null, eventArgs);
                            },
                            placeholder: "Your Email",
                            size: "large",
                            type: "email",
                            value: generateStateValueProp($state, [
                              "input",
                              "value"
                            ])
                          };
                          initializeCodeComponentStates(
                            $state,
                            [
                              {
                                name: "value",
                                plasmicStateName: "input.value"
                              }
                            ],

                            [],
                            AntdInput_Helpers ?? {},
                            child$Props
                          );
                          return (
                            <AntdInput
                              data-plasmic-name={"input"}
                              data-plasmic-override={overrides.input}
                              {...child$Props}
                            />
                          );
                        })()}
                      </FormItemWrapper>
                      <AntdButton
                        data-plasmic-name={"button"}
                        data-plasmic-override={overrides.button}
                        className={classNames("__wab_instance", sty.button)}
                        submitsForm={true}
                        type={"primary"}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__pfnSi
                          )}
                        >
                          {"Subscribe"}
                        </div>
                      </AntdButton>
                    </FormWrapper>
                  );
                })()}
              </div>
            </div>
          </div>
          <Embed
            data-plasmic-name={"embedHtml"}
            data-plasmic-override={overrides.embedHtml}
            className={classNames("__wab_instance", sty.embedHtml)}
            code={
              '<script src="https://cdn.jsdelivr.net/npm/gsap@3.13.0/dist/gsap.min.js"></script>\r\n\r\n<script src="https://cdn.jsdelivr.net/npm/gsap@3.13.0/dist/ScrollTrigger.min.js"></script>\r\n<script src="https://cdn.jsdelivr.net/npm/gsap@3.13.0/dist/SplitText.min.js"></script>\r\n\r\n<script src="https://cdn.jsdelivr.net/npm/gsap@3.14.1/dist/ScrollSmoother.min.js"></script>\r\n<script src="https://cdn.jsdelivr.net/npm/gsap@3.14.1/dist/MorphSVGPlugin.min.js"></script>\r\n\r\n <script src="https://cdn.jsdelivr.net/npm/gsap@3.14.1/dist/DrawSVGPlugin.min.js"></script>\r\n  <script src="https://cdn.jsdelivr.net/npm/gsap@3.14.1/dist/Flip.min.js"></script>\r\n  <script src="https://cdn.jsdelivr.net/npm/gsap@3.14.1/dist/MotionPathPlugin.min.js">\r\n</script>\r\n\r\n <!-- Three.js + GLTFLoader (Global versions used for simple testing) -->\r\n    <script src="https://cdn.jsdelivr.net/npm/three@0.160.0/build/three.min.js"></script>\r\n    <script src="https://cdn.jsdelivr.net/npm/three@0.160.0/examples/jsm/loaders/GLTFLoader.js" type="module"></script>\r\n    \r\n    <!-- We need to expose GLTFLoader to window for our script to pick it up if not bundled -->\r\n    <script type="module">\r\n        import { GLTFLoader } from \'https://cdn.jsdelivr.net/npm/three@0.160.0/examples/jsm/loaders/GLTFLoader.js\';\r\n        window.GLTFLoader = GLTFLoader;\r\n    </script>\r\n\r\n\r\n\r\n<script src="https://cdn.jsdelivr.net/npm/animotion-saply-plus@5.0.8/dist/animotion-saply.min.js"></script>'
            }
          />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  aboutUs: [
    "aboutUs",
    "nav",
    "navBar",
    "heroBtn3",
    "wrapper",
    "innerContents2",
    "innerContents3",
    "statements",
    "foundersMessage",
    "ourFounder",
    "contentsAbout2",
    "innerContents4",
    "imageAbout2",
    "values",
    "pageWrapper2",
    "aboutUs2",
    "contentsAbout3",
    "joinCOmmunity",
    "heroBtn4",
    "events",
    "footer",
    "form",
    "formField",
    "input",
    "button",
    "embedHtml"
  ],

  nav: ["nav", "navBar", "heroBtn3"],
  navBar: ["navBar"],
  heroBtn3: ["heroBtn3"],
  wrapper: ["wrapper", "innerContents2", "innerContents3"],
  innerContents2: ["innerContents2"],
  innerContents3: ["innerContents3"],
  statements: ["statements"],
  foundersMessage: [
    "foundersMessage",
    "ourFounder",
    "contentsAbout2",
    "innerContents4",
    "imageAbout2"
  ],

  ourFounder: ["ourFounder", "contentsAbout2", "innerContents4", "imageAbout2"],
  contentsAbout2: ["contentsAbout2", "innerContents4"],
  innerContents4: ["innerContents4"],
  imageAbout2: ["imageAbout2"],
  values: ["values"],
  pageWrapper2: ["pageWrapper2", "aboutUs2", "contentsAbout3"],
  aboutUs2: ["aboutUs2", "contentsAbout3"],
  contentsAbout3: ["contentsAbout3"],
  joinCOmmunity: ["joinCOmmunity", "heroBtn4"],
  heroBtn4: ["heroBtn4"],
  events: ["events"],
  footer: ["footer", "form", "formField", "input", "button"],
  form: ["form", "formField", "input", "button"],
  formField: ["formField", "input"],
  input: ["input"],
  button: ["button"],
  embedHtml: ["embedHtml"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicAboutUs__ArgProps,
          internalVariantPropNames: PlasmicAboutUs__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicAboutUs__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "aboutUs") {
    func.displayName = "PlasmicAboutUs";
  } else {
    func.displayName = `PlasmicAboutUs.${nodeName}`;
  }
  return func;
}

export const PlasmicAboutUs = Object.assign(
  // Top-level PlasmicAboutUs renders the root element
  makeNodeComponent("aboutUs"),
  {
    // Helper components rendering sub-elements
    nav: makeNodeComponent("nav"),
    navBar: makeNodeComponent("navBar"),
    heroBtn3: makeNodeComponent("heroBtn3"),
    wrapper: makeNodeComponent("wrapper"),
    innerContents2: makeNodeComponent("innerContents2"),
    innerContents3: makeNodeComponent("innerContents3"),
    statements: makeNodeComponent("statements"),
    foundersMessage: makeNodeComponent("foundersMessage"),
    ourFounder: makeNodeComponent("ourFounder"),
    contentsAbout2: makeNodeComponent("contentsAbout2"),
    innerContents4: makeNodeComponent("innerContents4"),
    imageAbout2: makeNodeComponent("imageAbout2"),
    values: makeNodeComponent("values"),
    pageWrapper2: makeNodeComponent("pageWrapper2"),
    aboutUs2: makeNodeComponent("aboutUs2"),
    contentsAbout3: makeNodeComponent("contentsAbout3"),
    joinCOmmunity: makeNodeComponent("joinCOmmunity"),
    heroBtn4: makeNodeComponent("heroBtn4"),
    events: makeNodeComponent("events"),
    footer: makeNodeComponent("footer"),
    form: makeNodeComponent("form"),
    formField: makeNodeComponent("formField"),
    input: makeNodeComponent("input"),
    button: makeNodeComponent("button"),
    embedHtml: makeNodeComponent("embedHtml"),
    // Metadata about props expected for PlasmicAboutUs
    internalVariantProps: PlasmicAboutUs__VariantProps,
    internalArgProps: PlasmicAboutUs__ArgProps,
    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pageRoute: "/about-us",
      pagePath: "/about-us",
      params: {},
      query: {}
    })
  }
);

export default PlasmicAboutUs;
/* prettier-ignore-end */
