/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: sUj6qNzu2DyGvGvfQpYywu
// Component: nWX8ifZU7VVE
import * as React from "react";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import {
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  generateOnMutateForSpec,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  hasVariant,
  initializeCodeComponentStates,
  useDollarState
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import { NavigationBar } from "@plasmicpkgs/plasmic-nav";
import { FormWrapper } from "@plasmicpkgs/antd5/skinny/Form";
import { formHelpers as FormWrapper_Helpers } from "@plasmicpkgs/antd5/skinny/Form";
import { FormItemWrapper } from "@plasmicpkgs/antd5/skinny/FormItem";
import { AntdInput } from "@plasmicpkgs/antd5/skinny/registerInput";
import { inputHelpers as AntdInput_Helpers } from "@plasmicpkgs/antd5/skinny/registerInput";
import { AntdButton } from "@plasmicpkgs/antd5/skinny/registerButton";
import { Embed } from "@plasmicpkgs/plasmic-basic-components";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: sUj6qNzu2DyGvGvfQpYywu/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: sUj6qNzu2DyGvGvfQpYywu/styleTokensProvider
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: sUj6qNzu2DyGvGvfQpYywu/projectcss
import sty from "./PlasmicDonation.module.css"; // plasmic-import: nWX8ifZU7VVE/css

const emptyProxy = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q) {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export function generateDynamicMetadata($q, $ctx) {
  return {
    openGraph: {},
    twitter: {
      card: "summary"
    }
  };
}

createPlasmicElementProxy;

export const PlasmicDonation__VariantProps = new Array();

export const PlasmicDonation__ArgProps = new Array();

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicDonation__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const globalVariants = _useGlobalVariants();
  const stateSpecs = React.useMemo(
    () => [
      {
        path: "form.value",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined,
        refName: "form",
        onMutate: generateOnMutateForSpec("value", FormWrapper_Helpers)
      },
      {
        path: "form.isSubmitting",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => false,
        refName: "form",
        onMutate: generateOnMutateForSpec("isSubmitting", FormWrapper_Helpers)
      },
      {
        path: "input.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined,
        onMutate: generateOnMutateForSpec("value", AntdInput_Helpers)
      }
    ],

    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });
  const pageMetadata = generateDynamicMetadata(
    wrapQueriesWithLoadingProxy({}),
    $ctx
  );
  const styleTokensClassNames = _useStyleTokens();
  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"nav"}
            data-plasmic-override={overrides.nav}
            className={classNames(projectcss.all, sty.nav)}
            data-anim={"true"}
            data-anim-props={``}
            data-anim-type={"fromTo"}
          >
            <NavigationBar
              data-plasmic-name={"navBar"}
              data-plasmic-override={overrides.navBar}
              brand={
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    sty.link__jf17I
                  )}
                  component={Link}
                  href={"#"}
                  legacyBehavior={false}
                  platform={"nextjs"}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__kkjI3)}
                    displayHeight={"74px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={
                      hasVariant(globalVariants, "screen", "mobile")
                        ? "100%"
                        : "156px"
                    }
                    src={{
                      src: "/plasmic/tosin_umoren/images/image.png",
                      fullWidth: 313,
                      fullHeight: 149,
                      aspectRatio: undefined
                    }}
                  />
                </PlasmicLink__>
              }
              className={classNames("__wab_instance", sty.navBar)}
              closeButton={
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__vVzD1)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  src={"https://static1.plasmic.app/close.svg"}
                />
              }
              itemsGap={8}
              menuItems={
                <React.Fragment>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__pp79Q
                    )}
                    component={Link}
                    href={"/"}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"Home"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__lPxxw
                    )}
                    component={Link}
                    href={`/about-us`}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"About us"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link___8Et8B
                    )}
                    component={Link}
                    href={"/#Wdo"}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"What We Do"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__x3VEv
                    )}
                    component={Link}
                    href={`/gallery`}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"Media"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link___4JyIw
                    )}
                    component={Link}
                    href={`/contact-us`}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"Contact"}
                  </PlasmicLink__>
                </React.Fragment>
              }
              openButton={
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__r0Vil)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  height={
                    hasVariant(globalVariants, "screen", "tablet")
                      ? "50%"
                      : undefined
                  }
                  src={"https://static1.plasmic.app/menu.svg"}
                  width={
                    hasVariant(globalVariants, "screen", "tablet")
                      ? "50%"
                      : undefined
                  }
                />
              }
              responsiveBreakpoint={768}
            />

            <PlasmicLink__
              data-plasmic-name={"heroBtn3"}
              data-plasmic-override={overrides.heroBtn3}
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.__wab_text,
                sty.heroBtn3
              )}
              component={Link}
              href={`/donation`}
              legacyBehavior={false}
              platform={"nextjs"}
            >
              {"Donate"}
            </PlasmicLink__>
          </div>
          <div
            data-plasmic-name={"wrapper2"}
            data-plasmic-override={overrides.wrapper2}
            className={classNames(projectcss.all, sty.wrapper2)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__mspj8)}>
              <div
                data-plasmic-name={"innerContents4"}
                data-plasmic-override={overrides.innerContents4}
                className={classNames(projectcss.all, sty.innerContents4)}
              >
                <div
                  className={classNames(projectcss.all, sty.freeBox__edjvY)}
                  data-anim={"true"}
                  data-anim-props={
                    '{\n\n           "from": {"autoAlpha":0,\n"x": -100},\n\n           "to": {"autoAlpha":1,\n"x": 0},\n\n           "duration": 0.8\n\n         }'
                  }
                  data-anim-type={"fromTo"}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox__sOnM)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__uJfBu)}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__m3EnI
                      )}
                    >
                      {"GET INVOLVED"}
                    </div>
                  </div>
                  <h1
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1___8ROyn
                    )}
                  >
                    {"Partnership \ncollaboration info"}
                  </h1>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__hwt1V
                    )}
                  >
                    {
                      "We welcome collaborations with individuals, brands, churches, and corporate organizations."
                    }
                  </div>
                  <PlasmicLink__
                    data-plasmic-name={"heroBtn4"}
                    data-plasmic-override={overrides.heroBtn4}
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.heroBtn4
                    )}
                    component={Link}
                    href={"https://www.plasmic.app/"}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"Donate Below"}
                  </PlasmicLink__>
                </div>
                <div
                  className={classNames(projectcss.all, sty.freeBox__eGbBc)}
                  data-anim={"true"}
                  data-anim-props={
                    '{\n\n           "from": {"autoAlpha":0,\n"x": 100},\n\n           "to": {"autoAlpha":1,\n"x": 0},\n\n           "duration": 0.8\n\n         }'
                  }
                  data-anim-type={"fromTo"}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__e2Vbe)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/tosin_umoren/images/image38.png",
                      fullWidth: 960,
                      fullHeight: 768,
                      aspectRatio: undefined
                    }}
                  />
                </div>
              </div>
            </div>
          </div>
          <div
            data-plasmic-name={"wrapper"}
            data-plasmic-override={overrides.wrapper}
            className={classNames(projectcss.all, sty.wrapper, "d-scroll")}
          >
            <div className={classNames(projectcss.all, sty.freeBox___5TJ)}>
              <h1
                className={classNames(
                  projectcss.all,
                  projectcss.h1,
                  projectcss.__wab_text,
                  sty.h1___6Bfb3
                )}
                data-anim={"true"}
                data-anim-props={
                  '{\n\n"scrollTrigger": {\n\n"trigger": ".d-scroll",\n\n"start": "top 80%",\n\n"end": "bottom 20%",\n\n"scrub": true,\n\n"toggleActions": "play none none reverse"\n\n},\n\n"x": -100,\n\n"opacity": 0,\n\n"duration": 1.5,\n\n"stagger": 0.5,\n\n"ease": "power4.out"\n\n}'
                }
                data-anim-type={"from"}
              >
                {"Donation Options"}
              </h1>
              <div
                data-plasmic-name={"innerContents7"}
                data-plasmic-override={overrides.innerContents7}
                className={classNames(
                  projectcss.all,
                  sty.innerContents7,
                  "in-scroll"
                )}
              >
                <div
                  className={classNames(projectcss.all, sty.columns__gnFmF)}
                  data-anim={"true"}
                  data-anim-props={
                    '{\n\n"scrollTrigger": {\n\n"trigger": ".in-scroll",\n\n"start": "top 80%",\n\n"end": "bottom 20%",\n\n"scrub": true,\n\n"toggleActions": "play none none reverse"\n\n},\n\n"y": -100,\n\n"opacity": 0,\n\n"duration": 1.5,\n\n"stagger": 0.5,\n\n"ease": "power4.out"\n\n}'
                  }
                  data-anim-type={"from"}
                >
                  <div
                    className={classNames(projectcss.all, sty.column__dCu43)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__fOdQx
                      )}
                    >
                      {"Local Bank Transfer (Naira Account \u2013 Zenith Bank)"}
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__jzFtx)}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__lxvX1)}
                        displayHeight={
                          hasVariant(globalVariants, "screen", "mobile")
                            ? "20%"
                            : "30%"
                        }
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={
                          hasVariant(globalVariants, "screen", "mobile")
                            ? "20%"
                            : "10%"
                        }
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/tosin_umoren/images/image40.png",
                          fullWidth: 172,
                          fullHeight: 186,
                          aspectRatio: undefined
                        }}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__zgYmc
                        )}
                      >
                        {"1311207700\nZenith Bank \nTosin Umoren Foundation"}
                      </div>
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column__qyYln)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__szp2T
                      )}
                    >
                      {"International Donations (Dollar Account \u2013 paypal)"}
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__mscrL)}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__faX5X)}
                        displayHeight={"100%"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"10%"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/tosin_umoren/images/image41.png",
                          fullWidth: 182,
                          fullHeight: 196,
                          aspectRatio: undefined
                        }}
                      />

                      <PlasmicLink__
                        data-plasmic-name={"heroBtn5"}
                        data-plasmic-override={overrides.heroBtn5}
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.heroBtn5
                        )}
                        component={Link}
                        href={"https://www.plasmic.app/"}
                        legacyBehavior={false}
                        platform={"nextjs"}
                      >
                        {"Donate"}
                      </PlasmicLink__>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <section
            data-plasmic-name={"helpOthers"}
            data-plasmic-override={overrides.helpOthers}
            className={classNames(projectcss.all, sty.helpOthers, "u-scroll")}
          >
            <div
              data-plasmic-name={"help"}
              data-plasmic-override={overrides.help}
              className={classNames(projectcss.all, sty.help)}
              data-anim={"true"}
              data-anim-props={
                '{\n\n"scrollTrigger": {\n\n"trigger": ".u-scroll",\n\n"start": "top 80%",\n\n"end": "bottom 20%",\n\n"scrub": true,\n\n"toggleActions": "play none none reverse"\n\n},\n\n"y": -100,\n\n"opacity": 0,\n\n"duration": 1.5,\n\n"stagger": 0.5,\n\n"ease": "power4.out"\n\n}'
              }
              data-anim-type={"from"}
            >
              <div
                data-plasmic-name={"contentsAbout2"}
                data-plasmic-override={overrides.contentsAbout2}
                className={classNames(projectcss.all, sty.contentsAbout2)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__oirdw)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox___0LkZq)}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__kd8QK
                    )}
                  >
                    {"Unselfish love of one\u2019s fellow men"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"innerContents5"}
                  data-plasmic-override={overrides.innerContents5}
                  className={classNames(projectcss.all, sty.innerContents5)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ogLn
                    )}
                  >
                    {
                      "Charity is the act of giving help to those in need of it. it is a humanitarian act. it involves giving money goods or time and effort to those who need it."
                    }
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___19FdO
                    )}
                  >
                    {"Anonymous"}
                  </div>
                </div>
              </div>
              <div
                data-plasmic-name={"imageAbout2"}
                data-plasmic-override={overrides.imageAbout2}
                className={classNames(projectcss.all, sty.imageAbout2)}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__t3Nhl)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={
                    hasVariant(globalVariants, "screen", "tablet")
                      ? "100%"
                      : "80%"
                  }
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/tosin_umoren/images/image43.png",
                    fullWidth: 840,
                    fullHeight: 726,
                    aspectRatio: undefined
                  }}
                />
              </div>
            </div>
          </section>
          <div
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames(projectcss.all, sty.footer, "F-scroll")}
          >
            <div
              className={classNames(projectcss.all, sty.columns__yb9Mp)}
              data-anim={"true"}
              data-anim-props={
                '{\n\n"scrollTrigger": {\n\n"trigger": ".F-scroll",\n\n"start": "top 80%",\n\n"end": "bottom 20%",\n\n"scrub": true,\n\n"toggleActions": "play none none reverse"\n\n},\n\n"y": -100,\n\n"opacity": 0,\n\n"duration": 1.5,\n\n"stagger": 0.5,\n\n"ease": "power4.out"\n\n}'
              }
              data-anim-type={"from"}
            >
              <div className={classNames(projectcss.all, sty.column__iZnqE)}>
                <div className={classNames(projectcss.all, sty.freeBox__egcwY)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__xh65X)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/tosin_umoren/images/image.png",
                      fullWidth: 313,
                      fullHeight: 149,
                      aspectRatio: undefined
                    }}
                  />
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__hRaor)}>
                <h1
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.__wab_text,
                    sty.h1__ooz1N
                  )}
                >
                  {"Contact Us"}
                </h1>
                <div
                  className={classNames(projectcss.all, sty.freeBox___8Rz3S)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__gNyo9
                    )}
                  >
                    {"EMAIL US:"}
                  </div>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link___0PbGa
                    )}
                    component={Link}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"tosinumorenfoundation@gmail.com\r"}
                  </PlasmicLink__>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__tpSo1)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__f10Wk
                    )}
                  >
                    {"PHONE:"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__fCkXc
                    )}
                  >
                    {"+234 813 072 2129, +1760 829 0816"}
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__urVnh)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__nsoXb
                    )}
                  >
                    {"LOCATION:"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__tiJ0X
                    )}
                  >
                    {"Nigeria (Outreaches across Lagos, Oyo, Osun & Ekiti)"}
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__gw6Rh)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__sjVsm
                    )}
                  >
                    {"SOCIALS:"}
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__wuGnn)}
                  >
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__lasze
                      )}
                      component={Link}
                      legacyBehavior={false}
                      platform={"nextjs"}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__h4OAg)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={
                          hasVariant(globalVariants, "screen", "mobile")
                            ? "80%"
                            : "auto"
                        }
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/tosin_umoren/images/image26.png",
                          fullWidth: 36,
                          fullHeight: 36,
                          aspectRatio: undefined
                        }}
                      />
                    </PlasmicLink__>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__hBtEu
                      )}
                      component={Link}
                      legacyBehavior={false}
                      platform={"nextjs"}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__r9D5D)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={
                          hasVariant(globalVariants, "screen", "mobile")
                            ? "80%"
                            : "auto"
                        }
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/tosin_umoren/images/image25.png",
                          fullWidth: 36,
                          fullHeight: 36,
                          aspectRatio: undefined
                        }}
                      />
                    </PlasmicLink__>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__y8Ep1
                      )}
                      component={Link}
                      legacyBehavior={false}
                      platform={"nextjs"}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__ylm5A)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={
                          hasVariant(globalVariants, "screen", "mobile")
                            ? "80%"
                            : "auto"
                        }
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/tosin_umoren/images/image24.png",
                          fullWidth: 36,
                          fullHeight: 36,
                          aspectRatio: undefined
                        }}
                      />
                    </PlasmicLink__>
                  </div>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__icYuP)}>
                <h1
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.__wab_text,
                    sty.h1__ydQqG
                  )}
                >
                  {"Links"}
                </h1>
                <div className={classNames(projectcss.all, sty.freeBox__nhz6T)}>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__zvUuv
                    )}
                    component={Link}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"Projects"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__wmI7Z
                    )}
                    component={Link}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"Events"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link___9HhJ
                    )}
                    component={Link}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"Donate"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__boaQh
                    )}
                    component={Link}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"News"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__aIoXv
                    )}
                    component={Link}
                    href={`/gallery`}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"Gallery"}
                  </PlasmicLink__>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__bEvLg)}>
                <h1
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.__wab_text,
                    sty.h1__c33Q6
                  )}
                >
                  {"Subscribe to get latest updates"}
                </h1>
                {(() => {
                  const child$Props = {
                    className: classNames("__wab_instance", sty.form),
                    extendedOnValuesChange: async (...eventArgs) => {
                      generateStateOnChangePropForCodeComponents(
                        $state,
                        "value",
                        ["form", "value"],
                        FormWrapper_Helpers
                      ).apply(null, eventArgs);
                    },
                    formItems: [
                      { label: "Name", name: "name", inputType: "Text" },
                      {
                        label: "Message",
                        name: "message",
                        inputType: "Text Area"
                      }
                    ],

                    labelCol: { span: 8, horizontalOnly: true },
                    layout: "vertical",
                    mode: "advanced",
                    onIsSubmittingChange: async (...eventArgs) => {
                      generateStateOnChangePropForCodeComponents(
                        $state,
                        "isSubmitting",
                        ["form", "isSubmitting"],
                        FormWrapper_Helpers
                      ).apply(null, eventArgs);
                    },
                    ref: ref => {
                      $refs["form"] = ref;
                    },
                    submitSlot: null,
                    wrapperCol: { span: 16, horizontalOnly: true }
                  };
                  initializeCodeComponentStates(
                    $state,
                    [
                      {
                        name: "value",
                        plasmicStateName: "form.value"
                      },
                      {
                        name: "isSubmitting",
                        plasmicStateName: "form.isSubmitting"
                      }
                    ],

                    [],
                    FormWrapper_Helpers ?? {},
                    child$Props
                  );
                  return (
                    <FormWrapper
                      data-plasmic-name={"form"}
                      data-plasmic-override={overrides.form}
                      {...child$Props}
                    >
                      <FormItemWrapper
                        data-plasmic-name={"formField"}
                        data-plasmic-override={overrides.formField}
                        className={classNames("__wab_instance", sty.formField)}
                        label={
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__f9QOa
                            )}
                          >
                            {"Your Email"}
                          </div>
                        }
                        name={"email"}
                      >
                        {(() => {
                          const child$Props = {
                            className: classNames("__wab_instance", sty.input),
                            onChange: async (...eventArgs) => {
                              generateStateOnChangePropForCodeComponents(
                                $state,
                                "value",
                                ["input", "value"],
                                AntdInput_Helpers
                              ).apply(null, eventArgs);
                            },
                            placeholder: "Your Email",
                            size: "large",
                            type: "email",
                            value: generateStateValueProp($state, [
                              "input",
                              "value"
                            ])
                          };
                          initializeCodeComponentStates(
                            $state,
                            [
                              {
                                name: "value",
                                plasmicStateName: "input.value"
                              }
                            ],

                            [],
                            AntdInput_Helpers ?? {},
                            child$Props
                          );
                          return (
                            <AntdInput
                              data-plasmic-name={"input"}
                              data-plasmic-override={overrides.input}
                              {...child$Props}
                            />
                          );
                        })()}
                      </FormItemWrapper>
                      <AntdButton
                        data-plasmic-name={"button"}
                        data-plasmic-override={overrides.button}
                        className={classNames("__wab_instance", sty.button)}
                        submitsForm={true}
                        type={"primary"}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__ciLe8
                          )}
                        >
                          {"Subscribe"}
                        </div>
                      </AntdButton>
                    </FormWrapper>
                  );
                })()}
              </div>
            </div>
          </div>
          <Embed
            data-plasmic-name={"embedHtml"}
            data-plasmic-override={overrides.embedHtml}
            className={classNames("__wab_instance", sty.embedHtml)}
            code={
              '<script src="https://cdn.jsdelivr.net/npm/gsap@3.13.0/dist/gsap.min.js"></script>\r\n\r\n<script src="https://cdn.jsdelivr.net/npm/gsap@3.13.0/dist/ScrollTrigger.min.js"></script>\r\n<script src="https://cdn.jsdelivr.net/npm/gsap@3.13.0/dist/SplitText.min.js"></script>\r\n\r\n<script src="https://cdn.jsdelivr.net/npm/gsap@3.14.1/dist/ScrollSmoother.min.js"></script>\r\n<script src="https://cdn.jsdelivr.net/npm/gsap@3.14.1/dist/MorphSVGPlugin.min.js"></script>\r\n\r\n <script src="https://cdn.jsdelivr.net/npm/gsap@3.14.1/dist/DrawSVGPlugin.min.js"></script>\r\n  <script src="https://cdn.jsdelivr.net/npm/gsap@3.14.1/dist/Flip.min.js"></script>\r\n  <script src="https://cdn.jsdelivr.net/npm/gsap@3.14.1/dist/MotionPathPlugin.min.js">\r\n</script>\r\n\r\n <!-- Three.js + GLTFLoader (Global versions used for simple testing) -->\r\n    <script src="https://cdn.jsdelivr.net/npm/three@0.160.0/build/three.min.js"></script>\r\n    <script src="https://cdn.jsdelivr.net/npm/three@0.160.0/examples/jsm/loaders/GLTFLoader.js" type="module"></script>\r\n    \r\n    <!-- We need to expose GLTFLoader to window for our script to pick it up if not bundled -->\r\n    <script type="module">\r\n        import { GLTFLoader } from \'https://cdn.jsdelivr.net/npm/three@0.160.0/examples/jsm/loaders/GLTFLoader.js\';\r\n        window.GLTFLoader = GLTFLoader;\r\n    </script>\r\n\r\n\r\n\r\n<script src="https://cdn.jsdelivr.net/npm/animotion-saply-plus@5.0.8/dist/animotion-saply.min.js"></script>'
            }
          />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "nav",
    "navBar",
    "heroBtn3",
    "wrapper2",
    "innerContents4",
    "heroBtn4",
    "wrapper",
    "innerContents7",
    "heroBtn5",
    "helpOthers",
    "help",
    "contentsAbout2",
    "innerContents5",
    "imageAbout2",
    "footer",
    "form",
    "formField",
    "input",
    "button",
    "embedHtml"
  ],

  nav: ["nav", "navBar", "heroBtn3"],
  navBar: ["navBar"],
  heroBtn3: ["heroBtn3"],
  wrapper2: ["wrapper2", "innerContents4", "heroBtn4"],
  innerContents4: ["innerContents4", "heroBtn4"],
  heroBtn4: ["heroBtn4"],
  wrapper: ["wrapper", "innerContents7", "heroBtn5"],
  innerContents7: ["innerContents7", "heroBtn5"],
  heroBtn5: ["heroBtn5"],
  helpOthers: [
    "helpOthers",
    "help",
    "contentsAbout2",
    "innerContents5",
    "imageAbout2"
  ],

  help: ["help", "contentsAbout2", "innerContents5", "imageAbout2"],
  contentsAbout2: ["contentsAbout2", "innerContents5"],
  innerContents5: ["innerContents5"],
  imageAbout2: ["imageAbout2"],
  footer: ["footer", "form", "formField", "input", "button"],
  form: ["form", "formField", "input", "button"],
  formField: ["formField", "input"],
  input: ["input"],
  button: ["button"],
  embedHtml: ["embedHtml"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicDonation__ArgProps,
          internalVariantPropNames: PlasmicDonation__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicDonation__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicDonation";
  } else {
    func.displayName = `PlasmicDonation.${nodeName}`;
  }
  return func;
}

export const PlasmicDonation = Object.assign(
  // Top-level PlasmicDonation renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    nav: makeNodeComponent("nav"),
    navBar: makeNodeComponent("navBar"),
    heroBtn3: makeNodeComponent("heroBtn3"),
    wrapper2: makeNodeComponent("wrapper2"),
    innerContents4: makeNodeComponent("innerContents4"),
    heroBtn4: makeNodeComponent("heroBtn4"),
    wrapper: makeNodeComponent("wrapper"),
    innerContents7: makeNodeComponent("innerContents7"),
    heroBtn5: makeNodeComponent("heroBtn5"),
    helpOthers: makeNodeComponent("helpOthers"),
    help: makeNodeComponent("help"),
    contentsAbout2: makeNodeComponent("contentsAbout2"),
    innerContents5: makeNodeComponent("innerContents5"),
    imageAbout2: makeNodeComponent("imageAbout2"),
    footer: makeNodeComponent("footer"),
    form: makeNodeComponent("form"),
    formField: makeNodeComponent("formField"),
    input: makeNodeComponent("input"),
    button: makeNodeComponent("button"),
    embedHtml: makeNodeComponent("embedHtml"),
    // Metadata about props expected for PlasmicDonation
    internalVariantProps: PlasmicDonation__VariantProps,
    internalArgProps: PlasmicDonation__ArgProps,
    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pageRoute: "/donation",
      pagePath: "/donation",
      params: {},
      query: {}
    })
  }
);

export default PlasmicDonation;
/* prettier-ignore-end */
