/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: sUj6qNzu2DyGvGvfQpYywu
// Component: HvNTw5Y6qrDe
import * as React from "react";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import {
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  generateOnMutateForSpec,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  hasVariant,
  initializeCodeComponentStates,
  useDollarState
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import { NavigationBar } from "@plasmicpkgs/plasmic-nav";
import { FormWrapper } from "@plasmicpkgs/antd5/skinny/Form";
import { formHelpers as FormWrapper_Helpers } from "@plasmicpkgs/antd5/skinny/Form";
import { FormItemWrapper } from "@plasmicpkgs/antd5/skinny/FormItem";
import { AntdInput } from "@plasmicpkgs/antd5/skinny/registerInput";
import { inputHelpers as AntdInput_Helpers } from "@plasmicpkgs/antd5/skinny/registerInput";
import { AntdButton } from "@plasmicpkgs/antd5/skinny/registerButton";
import { Embed } from "@plasmicpkgs/plasmic-basic-components";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: sUj6qNzu2DyGvGvfQpYywu/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: sUj6qNzu2DyGvGvfQpYywu/styleTokensProvider
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: sUj6qNzu2DyGvGvfQpYywu/projectcss
import sty from "./PlasmicGallery.module.css"; // plasmic-import: HvNTw5Y6qrDe/css

const emptyProxy = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q) {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export function generateDynamicMetadata($q, $ctx) {
  return {
    openGraph: {},
    twitter: {
      card: "summary"
    }
  };
}

createPlasmicElementProxy;

export const PlasmicGallery__VariantProps = new Array();

export const PlasmicGallery__ArgProps = new Array();

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicGallery__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const globalVariants = _useGlobalVariants();
  const stateSpecs = React.useMemo(
    () => [
      {
        path: "form.value",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined,
        refName: "form",
        onMutate: generateOnMutateForSpec("value", FormWrapper_Helpers)
      },
      {
        path: "form.isSubmitting",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => false,
        refName: "form",
        onMutate: generateOnMutateForSpec("isSubmitting", FormWrapper_Helpers)
      },
      {
        path: "input.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined,
        onMutate: generateOnMutateForSpec("value", AntdInput_Helpers)
      }
    ],

    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });
  const pageMetadata = generateDynamicMetadata(
    wrapQueriesWithLoadingProxy({}),
    $ctx
  );
  const styleTokensClassNames = _useStyleTokens();
  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"nav"}
            data-plasmic-override={overrides.nav}
            className={classNames(projectcss.all, sty.nav)}
            data-anim={"true"}
            data-anim-props={``}
            data-anim-type={"fromTo"}
          >
            <NavigationBar
              data-plasmic-name={"navBar"}
              data-plasmic-override={overrides.navBar}
              brand={
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    sty.link___91ALj
                  )}
                  component={Link}
                  href={"#"}
                  legacyBehavior={false}
                  platform={"nextjs"}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__iAKl)}
                    displayHeight={"74px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={
                      hasVariant(globalVariants, "screen", "mobile")
                        ? "100%"
                        : "156px"
                    }
                    src={{
                      src: "/plasmic/tosin_umoren/images/image.png",
                      fullWidth: 313,
                      fullHeight: 149,
                      aspectRatio: undefined
                    }}
                  />
                </PlasmicLink__>
              }
              className={classNames("__wab_instance", sty.navBar)}
              closeButton={
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__mZoMu)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  src={"https://static1.plasmic.app/close.svg"}
                />
              }
              itemsGap={8}
              menuItems={
                <React.Fragment>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__quWm9
                    )}
                    component={Link}
                    href={"/"}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"Home"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link___0UPrU
                    )}
                    component={Link}
                    href={`/about-us`}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"About us"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__uwz5X
                    )}
                    component={Link}
                    href={"/#Wdo"}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"What We Do"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link___9KCtw
                    )}
                    component={Link}
                    href={`/gallery`}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"Media"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__acu0O
                    )}
                    component={Link}
                    href={`/contact-us`}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"Contact"}
                  </PlasmicLink__>
                </React.Fragment>
              }
              openButton={
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__poH38)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  height={
                    hasVariant(globalVariants, "screen", "tablet")
                      ? "50%"
                      : undefined
                  }
                  src={"https://static1.plasmic.app/menu.svg"}
                  width={
                    hasVariant(globalVariants, "screen", "tablet")
                      ? "50%"
                      : undefined
                  }
                />
              }
              responsiveBreakpoint={768}
            />

            <PlasmicLink__
              data-plasmic-name={"heroBtn3"}
              data-plasmic-override={overrides.heroBtn3}
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.__wab_text,
                sty.heroBtn3
              )}
              component={Link}
              href={`/donation`}
              legacyBehavior={false}
              platform={"nextjs"}
            >
              {"Donate"}
            </PlasmicLink__>
          </div>
          <section
            data-plasmic-name={"pageWrapper2"}
            data-plasmic-override={overrides.pageWrapper2}
            className={classNames(projectcss.all, sty.pageWrapper2, "g-main")}
          >
            <div
              data-plasmic-name={"aboutUs2"}
              data-plasmic-override={overrides.aboutUs2}
              className={classNames(projectcss.all, sty.aboutUs2)}
            >
              <div
                data-plasmic-name={"contentsAbout3"}
                data-plasmic-override={overrides.contentsAbout3}
                className={classNames(projectcss.all, sty.contentsAbout3, ``)}
                data-anim={"true"}
                data-anim-props={
                  '{\n\n           "from": {"autoAlpha":0,\n"x": 100},\n\n           "to": {"autoAlpha":1,\n"x": 0},\n\n           "duration": 0.8\n\n         }'
                }
                data-anim-type={"fromTo"}
              >
                <div
                  className={classNames(projectcss.all, sty.freeBox___7H8Pn)}
                >
                  <h1
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1__np73
                    )}
                  >
                    {"GALLERY"}
                  </h1>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__eLjbj
                    )}
                  >
                    {"Ekiti Outreach "}
                  </div>
                </div>
              </div>
            </div>
            <div
              data-plasmic-name={"wrapper"}
              data-plasmic-override={overrides.wrapper}
              className={classNames(projectcss.all, sty.wrapper)}
            >
              <div
                className={classNames(projectcss.all, sty.columns__jD7QR)}
                data-anim={"true"}
                data-anim-props={
                  hasVariant(globalVariants, "screen", "tablet")
                    ? ``
                    : '{\n\n           "from": {"autoAlpha":0,\n"scale": 1.5},\n\n           "to": {"autoAlpha":1,\n"scale": 1},\n\n           "duration": 0.8\n\n         }'
                }
                data-anim-type={"fromTo"}
              >
                <div
                  className={classNames(projectcss.all, sty.column__wCppZ)}
                />

                <div
                  className={classNames(projectcss.all, sty.column__xYYg0)}
                />

                <div
                  className={classNames(projectcss.all, sty.column__jeAkS)}
                />

                <div
                  className={classNames(projectcss.all, sty.column__l57M2)}
                />
              </div>
            </div>
            <div
              data-plasmic-name={"wrapper2"}
              data-plasmic-override={overrides.wrapper2}
              className={classNames(projectcss.all, sty.wrapper2, "g-2")}
            >
              <div
                className={classNames(projectcss.all, sty.columns__xWgof)}
                data-anim={"true"}
                data-anim-props={
                  hasVariant(globalVariants, "screen", "tablet")
                    ? ``
                    : '{\n\n"scrollTrigger": {\n\n"trigger": ".g-2",\n\n"start": "top 80%",\n\n"end": "bottom 20%",\n\n"scrub": true,\n\n"toggleActions": "play none none reverse"\n\n},\n\n"y": -100,\n\n"opacity": 0,\n\n"duration": 2,\n\n"stagger": 1.5,\n\n"ease": "power4.out"\n\n}'
                }
                data-anim-type={"from"}
              >
                <div
                  className={classNames(projectcss.all, sty.column__zd4Kc)}
                />

                <div
                  className={classNames(projectcss.all, sty.column__leTsz)}
                />

                <div
                  className={classNames(projectcss.all, sty.column___2ZKoj)}
                />

                <div
                  className={classNames(projectcss.all, sty.column__ocvVc)}
                />
              </div>
            </div>
          </section>
          <section
            data-plasmic-name={"pageWrapper3"}
            data-plasmic-override={overrides.pageWrapper3}
            className={classNames(projectcss.all, sty.pageWrapper3, "g-second")}
          >
            <div
              data-plasmic-name={"aboutUs3"}
              data-plasmic-override={overrides.aboutUs3}
              className={classNames(projectcss.all, sty.aboutUs3)}
            >
              <div
                data-plasmic-name={"contentsAbout4"}
                data-plasmic-override={overrides.contentsAbout4}
                className={classNames(projectcss.all, sty.contentsAbout4)}
                data-anim={"true"}
                data-anim-props={
                  '{\n\n"scrollTrigger": {\n\n"trigger": ".g-second",\n\n"start": "top 80%",\n\n"end": "bottom 20%",\n\n"scrub": true,\n\n"toggleActions": "play none none reverse"\n\n},\n\n"y": -100,\n\n"opacity": 0,\n\n"duration": 2,\n\n"stagger": 1.5,\n\n"ease": "power4.out"\n\n}'
                }
                data-anim-type={"from"}
              >
                <div
                  className={classNames(projectcss.all, sty.freeBox___2Y9Iw)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__xcBtG
                    )}
                  >
                    {"Osun Outreach "}
                  </div>
                </div>
              </div>
            </div>
            <div
              data-plasmic-name={"wrapper3"}
              data-plasmic-override={overrides.wrapper3}
              className={classNames(projectcss.all, sty.wrapper3, "g-out")}
            >
              <div
                className={classNames(projectcss.all, sty.columns__mSazQ)}
                data-anim={"true"}
                data-anim-props={
                  hasVariant(globalVariants, "screen", "tablet")
                    ? ``
                    : '{\n\n"scrollTrigger": {\n\n"trigger": ".g-out",\n\n"start": "top 80%",\n\n"end": "bottom 20%",\n\n"scrub": true,\n\n"toggleActions": "play none none reverse"\n\n},\n\n"y": -100,\n\n"opacity": 0,\n\n"duration": 2,\n\n"stagger": 1.5,\n\n"ease": "power4.out"\n\n}'
                }
                data-anim-type={"from"}
              >
                <div
                  className={classNames(projectcss.all, sty.column__ecb0O)}
                />

                <div
                  className={classNames(projectcss.all, sty.column___7FBiu)}
                />

                <div
                  className={classNames(projectcss.all, sty.column__iTl68)}
                />

                <div
                  className={classNames(projectcss.all, sty.column__cs2U9)}
                />
              </div>
            </div>
            <div
              data-plasmic-name={"wrapper4"}
              data-plasmic-override={overrides.wrapper4}
              className={classNames(projectcss.all, sty.wrapper4, "g-out3")}
            >
              <div
                className={classNames(projectcss.all, sty.columns__rB6R)}
                data-anim={"true"}
                data-anim-props={
                  hasVariant(globalVariants, "screen", "tablet")
                    ? ``
                    : '{\n\n"scrollTrigger": {\n\n"trigger": ".g-out3",\n\n"start": "top 80%",\n\n"end": "bottom 20%",\n\n"scrub": true,\n\n"toggleActions": "play none none reverse"\n\n},\n\n"y": -100,\n\n"opacity": 0,\n\n"duration": 2,\n\n"stagger": 1.5,\n\n"ease": "power4.out"\n\n}'
                }
                data-anim-type={"from"}
              >
                <div
                  className={classNames(projectcss.all, sty.column__gm13R)}
                />

                <div
                  className={classNames(projectcss.all, sty.column__n4Seu)}
                />

                <div
                  className={classNames(projectcss.all, sty.column__zCyKz)}
                />

                <div
                  className={classNames(projectcss.all, sty.column__tPytz)}
                />
              </div>
            </div>
          </section>
          <section
            data-plasmic-name={"pageWrapper4"}
            data-plasmic-override={overrides.pageWrapper4}
            className={classNames(projectcss.all, sty.pageWrapper4, "g-third")}
          >
            <div
              data-plasmic-name={"aboutUs4"}
              data-plasmic-override={overrides.aboutUs4}
              className={classNames(projectcss.all, sty.aboutUs4)}
            >
              <div
                data-plasmic-name={"contentsAbout5"}
                data-plasmic-override={overrides.contentsAbout5}
                className={classNames(projectcss.all, sty.contentsAbout5)}
                data-anim={"true"}
                data-anim-props={
                  '{\n\n"scrollTrigger": {\n\n"trigger": ".g-third",\n\n"start": "top 80%",\n\n"end": "bottom 20%",\n\n"scrub": true,\n\n"toggleActions": "play none none reverse"\n\n},\n\n"y": -100,\n\n"opacity": 0,\n\n"duration": 2,\n\n"stagger": 1.5,\n\n"ease": "power4.out"\n\n}'
                }
                data-anim-type={"from"}
              >
                <div className={classNames(projectcss.all, sty.freeBox__wv0U)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__dWwim
                    )}
                  >
                    {"Lagos Outreach "}
                  </div>
                </div>
              </div>
            </div>
            <div
              data-plasmic-name={"wrapper5"}
              data-plasmic-override={overrides.wrapper5}
              className={classNames(projectcss.all, sty.wrapper5, "g-out4")}
            >
              <div
                className={classNames(projectcss.all, sty.columns__g7Eed)}
                data-anim={"true"}
                data-anim-props={
                  hasVariant(globalVariants, "screen", "tablet")
                    ? ``
                    : '{\n\n"scrollTrigger": {\n\n"trigger": ".g-third",\n\n"start": "top 80%",\n\n"end": "bottom 20%",\n\n"scrub": true,\n\n"toggleActions": "play none none reverse"\n\n},\n\n"y": -100,\n\n"opacity": 0,\n\n"duration": 2,\n\n"stagger": 1.5,\n\n"ease": "power4.out"\n\n}'
                }
                data-anim-type={"from"}
              >
                <div
                  className={classNames(projectcss.all, sty.column___1TNEj)}
                />

                <div
                  className={classNames(projectcss.all, sty.column__r2D5Z)}
                />

                <div
                  className={classNames(projectcss.all, sty.column___18NUl)}
                />

                <div
                  className={classNames(projectcss.all, sty.column___9KnxZ)}
                />
              </div>
            </div>
            <div
              data-plasmic-name={"wrapper6"}
              data-plasmic-override={overrides.wrapper6}
              className={classNames(projectcss.all, sty.wrapper6, "g-fourth")}
            >
              <div
                className={classNames(projectcss.all, sty.columns__wO5Ub)}
                data-anim={"true"}
                data-anim-props={
                  hasVariant(globalVariants, "screen", "tablet")
                    ? ``
                    : '{\n\n"scrollTrigger": {\n\n"trigger": ".g-fourth",\n\n"start": "top 80%",\n\n"end": "bottom 20%",\n\n"scrub": true,\n\n"toggleActions": "play none none reverse"\n\n},\n\n"y": -100,\n\n"opacity": 0,\n\n"duration": 2,\n\n"stagger": 1.5,\n\n"ease": "power4.out"\n\n}'
                }
                data-anim-type={"from"}
              >
                <div
                  className={classNames(projectcss.all, sty.column__lr7Za)}
                />

                <div
                  className={classNames(projectcss.all, sty.column__tuHb1)}
                />

                <div
                  className={classNames(projectcss.all, sty.column___1Ig7H)}
                />

                <div
                  className={classNames(projectcss.all, sty.column___6Sfj)}
                />
              </div>
            </div>
          </section>
          <div
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames(projectcss.all, sty.footer, "F-scroll")}
          >
            <div
              className={classNames(projectcss.all, sty.columns__xuXx7)}
              data-anim={"true"}
              data-anim-props={
                hasVariant(globalVariants, "screen", "tablet")
                  ? ``
                  : '{\n\n"scrollTrigger": {\n\n"trigger": ".F-scroll",\n\n"start": "top 80%",\n\n"end": "bottom 20%",\n\n"scrub": true,\n\n"toggleActions": "play none none reverse"\n\n},\n\n"y": -100,\n\n"opacity": 0,\n\n"duration": 1.5,\n\n"stagger": 0.5,\n\n"ease": "power4.out"\n\n}'
              }
              data-anim-type={"from"}
            >
              <div className={classNames(projectcss.all, sty.column__fdUfV)}>
                <div className={classNames(projectcss.all, sty.freeBox__oI7Ka)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__xqvYm)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/tosin_umoren/images/image.png",
                      fullWidth: 313,
                      fullHeight: 149,
                      aspectRatio: undefined
                    }}
                  />
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column___0L5Gp)}>
                <h1
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.__wab_text,
                    sty.h1__dCt9V
                  )}
                >
                  {"Contact Us"}
                </h1>
                <div className={classNames(projectcss.all, sty.freeBox__hi27E)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___5N1Iv
                    )}
                  >
                    {"EMAIL US:"}
                  </div>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__zXWol
                    )}
                    component={Link}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"tosinumorenfoundation@gmail.com\r"}
                  </PlasmicLink__>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox___8Oga)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__c77Pv
                    )}
                  >
                    {"PHONE:"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___0MguA
                    )}
                  >
                    {"+234 813 072 2129, +1760 829 0816"}
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__t7Vwc)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__pnf8A
                    )}
                  >
                    {"LOCATION:"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__qAik
                    )}
                  >
                    {"Nigeria (Outreaches across Lagos, Oyo, Osun & Ekiti)"}
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__z0VWd)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__kzaLs
                    )}
                  >
                    {"SOCIALS:"}
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__mgVxi)}
                  >
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link___8Nanq
                      )}
                      component={Link}
                      legacyBehavior={false}
                      platform={"nextjs"}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img___7WQpc)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={
                          hasVariant(globalVariants, "screen", "mobile")
                            ? "80%"
                            : "auto"
                        }
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/tosin_umoren/images/image26.png",
                          fullWidth: 36,
                          fullHeight: 36,
                          aspectRatio: undefined
                        }}
                      />
                    </PlasmicLink__>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__nT7D8
                      )}
                      component={Link}
                      legacyBehavior={false}
                      platform={"nextjs"}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__q6Ou4)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={
                          hasVariant(globalVariants, "screen", "mobile")
                            ? "80%"
                            : "auto"
                        }
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/tosin_umoren/images/image25.png",
                          fullWidth: 36,
                          fullHeight: 36,
                          aspectRatio: undefined
                        }}
                      />
                    </PlasmicLink__>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__qvMxD
                      )}
                      component={Link}
                      legacyBehavior={false}
                      platform={"nextjs"}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__n9TcK)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={
                          hasVariant(globalVariants, "screen", "mobile")
                            ? "80%"
                            : "auto"
                        }
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/tosin_umoren/images/image24.png",
                          fullWidth: 36,
                          fullHeight: 36,
                          aspectRatio: undefined
                        }}
                      />
                    </PlasmicLink__>
                  </div>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__vvT4Y)}>
                <h1
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.__wab_text,
                    sty.h1__sNvs6
                  )}
                >
                  {"Links"}
                </h1>
                <div
                  className={classNames(projectcss.all, sty.freeBox___8L3Ig)}
                >
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__htC1F
                    )}
                    component={Link}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"Projects"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__fsv4Q
                    )}
                    component={Link}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"Events"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link___5PSAm
                    )}
                    component={Link}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"Donate"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__doDw
                    )}
                    component={Link}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"News"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__dsSse
                    )}
                    component={Link}
                    href={`/gallery`}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"Gallery"}
                  </PlasmicLink__>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__sr6AS)}>
                <h1
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.__wab_text,
                    sty.h1__c3Ci
                  )}
                >
                  {"Subscribe to get latest updates"}
                </h1>
                {(() => {
                  const child$Props = {
                    className: classNames("__wab_instance", sty.form),
                    extendedOnValuesChange: async (...eventArgs) => {
                      generateStateOnChangePropForCodeComponents(
                        $state,
                        "value",
                        ["form", "value"],
                        FormWrapper_Helpers
                      ).apply(null, eventArgs);
                    },
                    formItems: [
                      { label: "Name", name: "name", inputType: "Text" },
                      {
                        label: "Message",
                        name: "message",
                        inputType: "Text Area"
                      }
                    ],

                    labelCol: { span: 8, horizontalOnly: true },
                    layout: "vertical",
                    mode: "advanced",
                    onIsSubmittingChange: async (...eventArgs) => {
                      generateStateOnChangePropForCodeComponents(
                        $state,
                        "isSubmitting",
                        ["form", "isSubmitting"],
                        FormWrapper_Helpers
                      ).apply(null, eventArgs);
                    },
                    ref: ref => {
                      $refs["form"] = ref;
                    },
                    submitSlot: null,
                    wrapperCol: { span: 16, horizontalOnly: true }
                  };
                  initializeCodeComponentStates(
                    $state,
                    [
                      {
                        name: "value",
                        plasmicStateName: "form.value"
                      },
                      {
                        name: "isSubmitting",
                        plasmicStateName: "form.isSubmitting"
                      }
                    ],

                    [],
                    FormWrapper_Helpers ?? {},
                    child$Props
                  );
                  return (
                    <FormWrapper
                      data-plasmic-name={"form"}
                      data-plasmic-override={overrides.form}
                      {...child$Props}
                    >
                      <FormItemWrapper
                        data-plasmic-name={"formField"}
                        data-plasmic-override={overrides.formField}
                        className={classNames("__wab_instance", sty.formField)}
                        label={
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___48Rpx
                            )}
                          >
                            {"Your Email"}
                          </div>
                        }
                        name={"email"}
                      >
                        {(() => {
                          const child$Props = {
                            className: classNames("__wab_instance", sty.input),
                            onChange: async (...eventArgs) => {
                              generateStateOnChangePropForCodeComponents(
                                $state,
                                "value",
                                ["input", "value"],
                                AntdInput_Helpers
                              ).apply(null, eventArgs);
                            },
                            placeholder: "Your Email",
                            size: "large",
                            type: "email",
                            value: generateStateValueProp($state, [
                              "input",
                              "value"
                            ])
                          };
                          initializeCodeComponentStates(
                            $state,
                            [
                              {
                                name: "value",
                                plasmicStateName: "input.value"
                              }
                            ],

                            [],
                            AntdInput_Helpers ?? {},
                            child$Props
                          );
                          return (
                            <AntdInput
                              data-plasmic-name={"input"}
                              data-plasmic-override={overrides.input}
                              {...child$Props}
                            />
                          );
                        })()}
                      </FormItemWrapper>
                      <AntdButton
                        data-plasmic-name={"button"}
                        data-plasmic-override={overrides.button}
                        className={classNames("__wab_instance", sty.button)}
                        submitsForm={true}
                        type={"primary"}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__h9WFg
                          )}
                        >
                          {"Subscribe"}
                        </div>
                      </AntdButton>
                    </FormWrapper>
                  );
                })()}
              </div>
            </div>
          </div>
          <Embed
            data-plasmic-name={"embedHtml"}
            data-plasmic-override={overrides.embedHtml}
            className={classNames("__wab_instance", sty.embedHtml)}
            code={
              '<script src="https://cdn.jsdelivr.net/npm/gsap@3.13.0/dist/gsap.min.js"></script>\r\n\r\n<script src="https://cdn.jsdelivr.net/npm/gsap@3.13.0/dist/ScrollTrigger.min.js"></script>\r\n<script src="https://cdn.jsdelivr.net/npm/gsap@3.13.0/dist/SplitText.min.js"></script>\r\n\r\n<script src="https://cdn.jsdelivr.net/npm/gsap@3.14.1/dist/ScrollSmoother.min.js"></script>\r\n<script src="https://cdn.jsdelivr.net/npm/gsap@3.14.1/dist/MorphSVGPlugin.min.js"></script>\r\n\r\n <script src="https://cdn.jsdelivr.net/npm/gsap@3.14.1/dist/DrawSVGPlugin.min.js"></script>\r\n  <script src="https://cdn.jsdelivr.net/npm/gsap@3.14.1/dist/Flip.min.js"></script>\r\n  <script src="https://cdn.jsdelivr.net/npm/gsap@3.14.1/dist/MotionPathPlugin.min.js">\r\n</script>\r\n\r\n <!-- Three.js + GLTFLoader (Global versions used for simple testing) -->\r\n    <script src="https://cdn.jsdelivr.net/npm/three@0.160.0/build/three.min.js"></script>\r\n    <script src="https://cdn.jsdelivr.net/npm/three@0.160.0/examples/jsm/loaders/GLTFLoader.js" type="module"></script>\r\n    \r\n    <!-- We need to expose GLTFLoader to window for our script to pick it up if not bundled -->\r\n    <script type="module">\r\n        import { GLTFLoader } from \'https://cdn.jsdelivr.net/npm/three@0.160.0/examples/jsm/loaders/GLTFLoader.js\';\r\n        window.GLTFLoader = GLTFLoader;\r\n    </script>\r\n\r\n\r\n\r\n<script src="https://cdn.jsdelivr.net/npm/animotion-saply-plus@5.0.8/dist/animotion-saply.min.js"></script>'
            }
          />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "nav",
    "navBar",
    "heroBtn3",
    "pageWrapper2",
    "aboutUs2",
    "contentsAbout3",
    "wrapper",
    "wrapper2",
    "pageWrapper3",
    "aboutUs3",
    "contentsAbout4",
    "wrapper3",
    "wrapper4",
    "pageWrapper4",
    "aboutUs4",
    "contentsAbout5",
    "wrapper5",
    "wrapper6",
    "footer",
    "form",
    "formField",
    "input",
    "button",
    "embedHtml"
  ],

  nav: ["nav", "navBar", "heroBtn3"],
  navBar: ["navBar"],
  heroBtn3: ["heroBtn3"],
  pageWrapper2: [
    "pageWrapper2",
    "aboutUs2",
    "contentsAbout3",
    "wrapper",
    "wrapper2"
  ],

  aboutUs2: ["aboutUs2", "contentsAbout3"],
  contentsAbout3: ["contentsAbout3"],
  wrapper: ["wrapper"],
  wrapper2: ["wrapper2"],
  pageWrapper3: [
    "pageWrapper3",
    "aboutUs3",
    "contentsAbout4",
    "wrapper3",
    "wrapper4"
  ],

  aboutUs3: ["aboutUs3", "contentsAbout4"],
  contentsAbout4: ["contentsAbout4"],
  wrapper3: ["wrapper3"],
  wrapper4: ["wrapper4"],
  pageWrapper4: [
    "pageWrapper4",
    "aboutUs4",
    "contentsAbout5",
    "wrapper5",
    "wrapper6"
  ],

  aboutUs4: ["aboutUs4", "contentsAbout5"],
  contentsAbout5: ["contentsAbout5"],
  wrapper5: ["wrapper5"],
  wrapper6: ["wrapper6"],
  footer: ["footer", "form", "formField", "input", "button"],
  form: ["form", "formField", "input", "button"],
  formField: ["formField", "input"],
  input: ["input"],
  button: ["button"],
  embedHtml: ["embedHtml"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicGallery__ArgProps,
          internalVariantPropNames: PlasmicGallery__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicGallery__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicGallery";
  } else {
    func.displayName = `PlasmicGallery.${nodeName}`;
  }
  return func;
}

export const PlasmicGallery = Object.assign(
  // Top-level PlasmicGallery renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    nav: makeNodeComponent("nav"),
    navBar: makeNodeComponent("navBar"),
    heroBtn3: makeNodeComponent("heroBtn3"),
    pageWrapper2: makeNodeComponent("pageWrapper2"),
    aboutUs2: makeNodeComponent("aboutUs2"),
    contentsAbout3: makeNodeComponent("contentsAbout3"),
    wrapper: makeNodeComponent("wrapper"),
    wrapper2: makeNodeComponent("wrapper2"),
    pageWrapper3: makeNodeComponent("pageWrapper3"),
    aboutUs3: makeNodeComponent("aboutUs3"),
    contentsAbout4: makeNodeComponent("contentsAbout4"),
    wrapper3: makeNodeComponent("wrapper3"),
    wrapper4: makeNodeComponent("wrapper4"),
    pageWrapper4: makeNodeComponent("pageWrapper4"),
    aboutUs4: makeNodeComponent("aboutUs4"),
    contentsAbout5: makeNodeComponent("contentsAbout5"),
    wrapper5: makeNodeComponent("wrapper5"),
    wrapper6: makeNodeComponent("wrapper6"),
    footer: makeNodeComponent("footer"),
    form: makeNodeComponent("form"),
    formField: makeNodeComponent("formField"),
    input: makeNodeComponent("input"),
    button: makeNodeComponent("button"),
    embedHtml: makeNodeComponent("embedHtml"),
    // Metadata about props expected for PlasmicGallery
    internalVariantProps: PlasmicGallery__VariantProps,
    internalArgProps: PlasmicGallery__ArgProps,
    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pageRoute: "/gallery",
      pagePath: "/gallery",
      params: {},
      query: {}
    })
  }
);

export default PlasmicGallery;
/* prettier-ignore-end */
