/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: sUj6qNzu2DyGvGvfQpYywu
// Component: HvNTw5Y6qrDe
import * as React from "react";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import {
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  generateOnMutateForSpec,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  hasVariant,
  initializeCodeComponentStates,
  useDollarState
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import { NavigationBar } from "@plasmicpkgs/plasmic-nav";
import { FormWrapper } from "@plasmicpkgs/antd5/skinny/Form";
import { formHelpers as FormWrapper_Helpers } from "@plasmicpkgs/antd5/skinny/Form";
import { FormItemWrapper } from "@plasmicpkgs/antd5/skinny/FormItem";
import { AntdInput } from "@plasmicpkgs/antd5/skinny/registerInput";
import { inputHelpers as AntdInput_Helpers } from "@plasmicpkgs/antd5/skinny/registerInput";
import { AntdButton } from "@plasmicpkgs/antd5/skinny/registerButton";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: sUj6qNzu2DyGvGvfQpYywu/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: sUj6qNzu2DyGvGvfQpYywu/styleTokensProvider
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: sUj6qNzu2DyGvGvfQpYywu/projectcss
import sty from "./PlasmicGallery.module.css"; // plasmic-import: HvNTw5Y6qrDe/css

const emptyProxy = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q) {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export function generateDynamicMetadata($q, $ctx) {
  return {
    openGraph: {},
    twitter: {
      card: "summary"
    }
  };
}

createPlasmicElementProxy;

export const PlasmicGallery__VariantProps = new Array();

export const PlasmicGallery__ArgProps = new Array();

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicGallery__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const globalVariants = _useGlobalVariants();
  const stateSpecs = React.useMemo(
    () => [
      {
        path: "form.value",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined,
        refName: "form",
        onMutate: generateOnMutateForSpec("value", FormWrapper_Helpers)
      },
      {
        path: "form.isSubmitting",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => false,
        refName: "form",
        onMutate: generateOnMutateForSpec("isSubmitting", FormWrapper_Helpers)
      },
      {
        path: "input.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined,
        onMutate: generateOnMutateForSpec("value", AntdInput_Helpers)
      }
    ],

    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });
  const pageMetadata = generateDynamicMetadata(
    wrapQueriesWithLoadingProxy({}),
    $ctx
  );
  const styleTokensClassNames = _useStyleTokens();
  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"nav"}
            data-plasmic-override={overrides.nav}
            className={classNames(projectcss.all, sty.nav)}
            data-anim={"true"}
            data-anim-props={``}
            data-anim-type={"fromTo"}
          >
            <NavigationBar
              data-plasmic-name={"navBar"}
              data-plasmic-override={overrides.navBar}
              brand={
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    sty.link___91ALj
                  )}
                  component={Link}
                  href={"#"}
                  legacyBehavior={false}
                  platform={"nextjs"}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__iAKl)}
                    displayHeight={"74px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={
                      hasVariant(globalVariants, "screen", "mobile")
                        ? "100%"
                        : "156px"
                    }
                    src={{
                      src: "/plasmic/tosin_umoren/images/image.png",
                      fullWidth: 313,
                      fullHeight: 149,
                      aspectRatio: undefined
                    }}
                  />
                </PlasmicLink__>
              }
              className={classNames("__wab_instance", sty.navBar)}
              closeButton={
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__mZoMu)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  src={"https://static1.plasmic.app/close.svg"}
                />
              }
              itemsGap={8}
              menuItems={
                <React.Fragment>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__quWm9
                    )}
                    component={Link}
                    href={"/"}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"Home"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link___0UPrU
                    )}
                    component={Link}
                    href={`/about-us`}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"About us"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__uwz5X
                    )}
                    component={Link}
                    href={"/#Wdo"}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"What We Do"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link___9KCtw
                    )}
                    component={Link}
                    href={`/gallery`}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"Media"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__acu0O
                    )}
                    component={Link}
                    href={`/contact-us`}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"Contact"}
                  </PlasmicLink__>
                </React.Fragment>
              }
              openButton={
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__poH38)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  height={
                    hasVariant(globalVariants, "screen", "tablet")
                      ? "50%"
                      : undefined
                  }
                  src={"https://static1.plasmic.app/menu.svg"}
                  width={
                    hasVariant(globalVariants, "screen", "tablet")
                      ? "50%"
                      : undefined
                  }
                />
              }
              responsiveBreakpoint={768}
            />

            <PlasmicLink__
              data-plasmic-name={"heroBtn3"}
              data-plasmic-override={overrides.heroBtn3}
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.__wab_text,
                sty.heroBtn3
              )}
              component={Link}
              href={`/donation`}
              legacyBehavior={false}
              platform={"nextjs"}
            >
              {"Donate"}
            </PlasmicLink__>
          </div>
          <section
            data-plasmic-name={"pageWrapper2"}
            data-plasmic-override={overrides.pageWrapper2}
            className={classNames(projectcss.all, sty.pageWrapper2)}
          >
            <div
              data-plasmic-name={"aboutUs2"}
              data-plasmic-override={overrides.aboutUs2}
              className={classNames(projectcss.all, sty.aboutUs2)}
            >
              <div
                data-plasmic-name={"contentsAbout3"}
                data-plasmic-override={overrides.contentsAbout3}
                className={classNames(projectcss.all, sty.contentsAbout3)}
              >
                <div
                  className={classNames(projectcss.all, sty.freeBox___7H8Pn)}
                >
                  <h1
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1__np73
                    )}
                  >
                    {"GALLERY"}
                  </h1>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__eLjbj
                    )}
                  >
                    {"Ekiti Outreach "}
                  </div>
                </div>
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.columns__jD7QR)}>
              <div className={classNames(projectcss.all, sty.column__wCppZ)} />
              <div className={classNames(projectcss.all, sty.column__xYYg0)} />
              <div className={classNames(projectcss.all, sty.column__jeAkS)} />
              <div className={classNames(projectcss.all, sty.column__l57M2)} />
            </div>
            <div className={classNames(projectcss.all, sty.columns__xWgof)}>
              <div className={classNames(projectcss.all, sty.column__zd4Kc)} />
              <div className={classNames(projectcss.all, sty.column__leTsz)} />
              <div className={classNames(projectcss.all, sty.column___2ZKoj)} />
              <div className={classNames(projectcss.all, sty.column__ocvVc)} />
            </div>
          </section>
          <section
            data-plasmic-name={"pageWrapper3"}
            data-plasmic-override={overrides.pageWrapper3}
            className={classNames(projectcss.all, sty.pageWrapper3)}
          >
            <div
              data-plasmic-name={"aboutUs3"}
              data-plasmic-override={overrides.aboutUs3}
              className={classNames(projectcss.all, sty.aboutUs3)}
            >
              <div
                data-plasmic-name={"contentsAbout4"}
                data-plasmic-override={overrides.contentsAbout4}
                className={classNames(projectcss.all, sty.contentsAbout4)}
              >
                <div
                  className={classNames(projectcss.all, sty.freeBox___2Y9Iw)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__xcBtG
                    )}
                  >
                    {"Osun Outreach "}
                  </div>
                </div>
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.columns__mSazQ)}>
              <div className={classNames(projectcss.all, sty.column__ecb0O)} />
              <div className={classNames(projectcss.all, sty.column___7FBiu)} />
              <div className={classNames(projectcss.all, sty.column__iTl68)} />
              <div className={classNames(projectcss.all, sty.column__cs2U9)} />
            </div>
            <div className={classNames(projectcss.all, sty.columns__rB6R)}>
              <div className={classNames(projectcss.all, sty.column__gm13R)} />
              <div className={classNames(projectcss.all, sty.column__n4Seu)} />
              <div className={classNames(projectcss.all, sty.column__zCyKz)} />
              <div className={classNames(projectcss.all, sty.column__tPytz)} />
            </div>
          </section>
          <section
            data-plasmic-name={"pageWrapper4"}
            data-plasmic-override={overrides.pageWrapper4}
            className={classNames(projectcss.all, sty.pageWrapper4)}
          >
            <div
              data-plasmic-name={"aboutUs4"}
              data-plasmic-override={overrides.aboutUs4}
              className={classNames(projectcss.all, sty.aboutUs4)}
            >
              <div
                data-plasmic-name={"contentsAbout5"}
                data-plasmic-override={overrides.contentsAbout5}
                className={classNames(projectcss.all, sty.contentsAbout5)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__wv0U)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__dWwim
                    )}
                  >
                    {"Lagos Outreach "}
                  </div>
                </div>
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.columns__g7Eed)}>
              <div className={classNames(projectcss.all, sty.column___1TNEj)} />
              <div className={classNames(projectcss.all, sty.column__r2D5Z)} />
              <div className={classNames(projectcss.all, sty.column___18NUl)} />
              <div className={classNames(projectcss.all, sty.column___9KnxZ)} />
            </div>
            <div className={classNames(projectcss.all, sty.columns__wO5Ub)}>
              <div className={classNames(projectcss.all, sty.column__lr7Za)} />
              <div className={classNames(projectcss.all, sty.column__tuHb1)} />
              <div className={classNames(projectcss.all, sty.column___1Ig7H)} />
              <div className={classNames(projectcss.all, sty.column___6Sfj)} />
            </div>
          </section>
          <div
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames(projectcss.all, sty.footer)}
          >
            <div className={classNames(projectcss.all, sty.columns__lk0Dc)}>
              <div className={classNames(projectcss.all, sty.column___1SfCi)}>
                <div className={classNames(projectcss.all, sty.freeBox__trcoI)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img___9JjJv)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/tosin_umoren/images/image.png",
                      fullWidth: 313,
                      fullHeight: 149,
                      aspectRatio: undefined
                    }}
                  />
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column___88Kos)}>
                <h1
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.__wab_text,
                    sty.h1__eLbzc
                  )}
                >
                  {"Contact Us"}
                </h1>
                <div className={classNames(projectcss.all, sty.freeBox__lsAh)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__qbK5I
                    )}
                  >
                    {"EMAIL US:"}
                  </div>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__ntsMv
                    )}
                    component={Link}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"tosinumorenfoundation@gmail.com\r"}
                  </PlasmicLink__>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__rjCk)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__jBOh
                    )}
                  >
                    {"PHONE:"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__x6LMa
                    )}
                  >
                    {"+234 813 072 2129, +1760 829 0816"}
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__mKnwS)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__r0PPd
                    )}
                  >
                    {"LOCATION:"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___915Z
                    )}
                  >
                    {"Nigeria (Outreaches across Lagos, Oyo, Osun & Ekiti)"}
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__js8Ec)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__zLwG
                    )}
                  >
                    {"SOCIALS:"}
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__bZhBq)}
                  >
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__v52IO
                      )}
                      component={Link}
                      legacyBehavior={false}
                      platform={"nextjs"}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img___9Q5YX)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={
                          hasVariant(globalVariants, "screen", "mobile")
                            ? "80%"
                            : "auto"
                        }
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/tosin_umoren/images/image26.png",
                          fullWidth: 36,
                          fullHeight: 36,
                          aspectRatio: undefined
                        }}
                      />
                    </PlasmicLink__>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__sbwgn
                      )}
                      component={Link}
                      legacyBehavior={false}
                      platform={"nextjs"}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img___9IYR)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={
                          hasVariant(globalVariants, "screen", "mobile")
                            ? "80%"
                            : "auto"
                        }
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/tosin_umoren/images/image25.png",
                          fullWidth: 36,
                          fullHeight: 36,
                          aspectRatio: undefined
                        }}
                      />
                    </PlasmicLink__>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__g7Au9
                      )}
                      component={Link}
                      legacyBehavior={false}
                      platform={"nextjs"}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__hn8N8)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={
                          hasVariant(globalVariants, "screen", "mobile")
                            ? "80%"
                            : "auto"
                        }
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/tosin_umoren/images/image24.png",
                          fullWidth: 36,
                          fullHeight: 36,
                          aspectRatio: undefined
                        }}
                      />
                    </PlasmicLink__>
                  </div>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__dmfAd)}>
                <div className={classNames(projectcss.all, sty.freeBox__lgGgU)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___66TWv
                    )}
                  >
                    {"MORE LINKS:"}
                  </div>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__aZvhJ
                    )}
                    component={Link}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"Projects"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link___2KLi
                    )}
                    component={Link}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"Events"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__lmk9O
                    )}
                    component={Link}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"Donate"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__jzVqb
                    )}
                    component={Link}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"News"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__aCulM
                    )}
                    component={Link}
                    href={`/gallery`}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"Gallery"}
                  </PlasmicLink__>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__n0Mqt)}>
                <h1
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.__wab_text,
                    sty.h1__dWbo
                  )}
                >
                  {"Subscribe to get latest updates"}
                </h1>
                {(() => {
                  const child$Props = {
                    className: classNames("__wab_instance", sty.form),
                    extendedOnValuesChange: async (...eventArgs) => {
                      generateStateOnChangePropForCodeComponents(
                        $state,
                        "value",
                        ["form", "value"],
                        FormWrapper_Helpers
                      ).apply(null, eventArgs);
                    },
                    formItems: [
                      { label: "Name", name: "name", inputType: "Text" },
                      {
                        label: "Message",
                        name: "message",
                        inputType: "Text Area"
                      }
                    ],

                    labelCol: { span: 8, horizontalOnly: true },
                    layout: "vertical",
                    mode: "advanced",
                    onIsSubmittingChange: async (...eventArgs) => {
                      generateStateOnChangePropForCodeComponents(
                        $state,
                        "isSubmitting",
                        ["form", "isSubmitting"],
                        FormWrapper_Helpers
                      ).apply(null, eventArgs);
                    },
                    ref: ref => {
                      $refs["form"] = ref;
                    },
                    submitSlot: null,
                    wrapperCol: { span: 16, horizontalOnly: true }
                  };
                  initializeCodeComponentStates(
                    $state,
                    [
                      {
                        name: "value",
                        plasmicStateName: "form.value"
                      },
                      {
                        name: "isSubmitting",
                        plasmicStateName: "form.isSubmitting"
                      }
                    ],

                    [],
                    FormWrapper_Helpers ?? {},
                    child$Props
                  );
                  return (
                    <FormWrapper
                      data-plasmic-name={"form"}
                      data-plasmic-override={overrides.form}
                      {...child$Props}
                    >
                      <FormItemWrapper
                        data-plasmic-name={"formField"}
                        data-plasmic-override={overrides.formField}
                        className={classNames("__wab_instance", sty.formField)}
                        label={
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__f0W0Z
                            )}
                          >
                            {"Your Email"}
                          </div>
                        }
                        name={"email"}
                      >
                        {(() => {
                          const child$Props = {
                            className: classNames("__wab_instance", sty.input),
                            onChange: async (...eventArgs) => {
                              generateStateOnChangePropForCodeComponents(
                                $state,
                                "value",
                                ["input", "value"],
                                AntdInput_Helpers
                              ).apply(null, eventArgs);
                            },
                            placeholder: "Your Email",
                            size: "large",
                            type: "email",
                            value: generateStateValueProp($state, [
                              "input",
                              "value"
                            ])
                          };
                          initializeCodeComponentStates(
                            $state,
                            [
                              {
                                name: "value",
                                plasmicStateName: "input.value"
                              }
                            ],

                            [],
                            AntdInput_Helpers ?? {},
                            child$Props
                          );
                          return (
                            <AntdInput
                              data-plasmic-name={"input"}
                              data-plasmic-override={overrides.input}
                              {...child$Props}
                            />
                          );
                        })()}
                      </FormItemWrapper>
                      <AntdButton
                        data-plasmic-name={"button"}
                        data-plasmic-override={overrides.button}
                        className={classNames("__wab_instance", sty.button)}
                        submitsForm={true}
                        type={"primary"}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___3K85V
                          )}
                        >
                          {"Subscribe"}
                        </div>
                      </AntdButton>
                    </FormWrapper>
                  );
                })()}
              </div>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "nav",
    "navBar",
    "heroBtn3",
    "pageWrapper2",
    "aboutUs2",
    "contentsAbout3",
    "pageWrapper3",
    "aboutUs3",
    "contentsAbout4",
    "pageWrapper4",
    "aboutUs4",
    "contentsAbout5",
    "footer",
    "form",
    "formField",
    "input",
    "button"
  ],

  nav: ["nav", "navBar", "heroBtn3"],
  navBar: ["navBar"],
  heroBtn3: ["heroBtn3"],
  pageWrapper2: ["pageWrapper2", "aboutUs2", "contentsAbout3"],
  aboutUs2: ["aboutUs2", "contentsAbout3"],
  contentsAbout3: ["contentsAbout3"],
  pageWrapper3: ["pageWrapper3", "aboutUs3", "contentsAbout4"],
  aboutUs3: ["aboutUs3", "contentsAbout4"],
  contentsAbout4: ["contentsAbout4"],
  pageWrapper4: ["pageWrapper4", "aboutUs4", "contentsAbout5"],
  aboutUs4: ["aboutUs4", "contentsAbout5"],
  contentsAbout5: ["contentsAbout5"],
  footer: ["footer", "form", "formField", "input", "button"],
  form: ["form", "formField", "input", "button"],
  formField: ["formField", "input"],
  input: ["input"],
  button: ["button"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicGallery__ArgProps,
          internalVariantPropNames: PlasmicGallery__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicGallery__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicGallery";
  } else {
    func.displayName = `PlasmicGallery.${nodeName}`;
  }
  return func;
}

export const PlasmicGallery = Object.assign(
  // Top-level PlasmicGallery renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    nav: makeNodeComponent("nav"),
    navBar: makeNodeComponent("navBar"),
    heroBtn3: makeNodeComponent("heroBtn3"),
    pageWrapper2: makeNodeComponent("pageWrapper2"),
    aboutUs2: makeNodeComponent("aboutUs2"),
    contentsAbout3: makeNodeComponent("contentsAbout3"),
    pageWrapper3: makeNodeComponent("pageWrapper3"),
    aboutUs3: makeNodeComponent("aboutUs3"),
    contentsAbout4: makeNodeComponent("contentsAbout4"),
    pageWrapper4: makeNodeComponent("pageWrapper4"),
    aboutUs4: makeNodeComponent("aboutUs4"),
    contentsAbout5: makeNodeComponent("contentsAbout5"),
    footer: makeNodeComponent("footer"),
    form: makeNodeComponent("form"),
    formField: makeNodeComponent("formField"),
    input: makeNodeComponent("input"),
    button: makeNodeComponent("button"),
    // Metadata about props expected for PlasmicGallery
    internalVariantProps: PlasmicGallery__VariantProps,
    internalArgProps: PlasmicGallery__ArgProps,
    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pageRoute: "/gallery",
      pagePath: "/gallery",
      params: {},
      query: {}
    })
  }
);

export default PlasmicGallery;
/* prettier-ignore-end */
