/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: sUj6qNzu2DyGvGvfQpYywu
import { createUseGlobalVariants } from "@plasmicapp/react-web";
import { useScreenVariants as useScreenVariantsnfEdBi4R3ZSs } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: nfEdBi4r3zSs/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantsnfEdBi4R3ZSs
});
