/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: sUj6qNzu2DyGvGvfQpYywu
// Component: wTjZJLNToKEE
import * as React from "react";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import {
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  generateOnMutateForSpec,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  hasVariant,
  initializeCodeComponentStates,
  useDollarState
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import { Embed } from "@plasmicpkgs/plasmic-basic-components";
import { NavigationBar } from "@plasmicpkgs/plasmic-nav";
import { FormWrapper } from "@plasmicpkgs/antd5/skinny/Form";
import { formHelpers as FormWrapper_Helpers } from "@plasmicpkgs/antd5/skinny/Form";
import { FormItemWrapper } from "@plasmicpkgs/antd5/skinny/FormItem";
import { AntdInput } from "@plasmicpkgs/antd5/skinny/registerInput";
import { inputHelpers as AntdInput_Helpers } from "@plasmicpkgs/antd5/skinny/registerInput";
import { AntdButton } from "@plasmicpkgs/antd5/skinny/registerButton";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: sUj6qNzu2DyGvGvfQpYywu/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: sUj6qNzu2DyGvGvfQpYywu/styleTokensProvider
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: sUj6qNzu2DyGvGvfQpYywu/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: wTjZJLNToKEE/css
import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: IHW8byIZthDW/icon

const emptyProxy = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q) {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export function generateDynamicMetadata($q, $ctx) {
  return {
    openGraph: {},
    twitter: {
      card: "summary"
    }
  };
}

createPlasmicElementProxy;

export const PlasmicHomepage__VariantProps = new Array();

export const PlasmicHomepage__ArgProps = new Array();

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHomepage__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const globalVariants = _useGlobalVariants();
  const stateSpecs = React.useMemo(
    () => [
      {
        path: "form.value",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined,
        refName: "form",
        onMutate: generateOnMutateForSpec("value", FormWrapper_Helpers)
      },
      {
        path: "form.isSubmitting",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => false,
        refName: "form",
        onMutate: generateOnMutateForSpec("isSubmitting", FormWrapper_Helpers)
      },
      {
        path: "input.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined,
        onMutate: generateOnMutateForSpec("value", AntdInput_Helpers)
      }
    ],

    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });
  const pageMetadata = generateDynamicMetadata(
    wrapQueriesWithLoadingProxy({}),
    $ctx
  );
  const styleTokensClassNames = _useStyleTokens();
  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"homepage"}
          data-plasmic-override={overrides.homepage}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.homepage
          )}
        >
          <Embed
            data-plasmic-name={"embedHtml"}
            data-plasmic-override={overrides.embedHtml}
            className={classNames("__wab_instance", sty.embedHtml)}
            code={
              '<script src="https://cdn.jsdelivr.net/npm/gsap@3.13.0/dist/gsap.min.js"></script>\r\n\r\n<script src="https://cdn.jsdelivr.net/npm/gsap@3.13.0/dist/ScrollTrigger.min.js"></script>\r\n<script src="https://cdn.jsdelivr.net/npm/gsap@3.13.0/dist/SplitText.min.js"></script>\r\n\r\n<script src="https://cdn.jsdelivr.net/npm/gsap@3.14.1/dist/ScrollSmoother.min.js"></script>\r\n<script src="https://cdn.jsdelivr.net/npm/gsap@3.14.1/dist/MorphSVGPlugin.min.js"></script>\r\n\r\n <script src="https://cdn.jsdelivr.net/npm/gsap@3.14.1/dist/DrawSVGPlugin.min.js"></script>\r\n  <script src="https://cdn.jsdelivr.net/npm/gsap@3.14.1/dist/Flip.min.js"></script>\r\n  <script src="https://cdn.jsdelivr.net/npm/gsap@3.14.1/dist/MotionPathPlugin.min.js">\r\n</script>\r\n\r\n <!-- Three.js + GLTFLoader (Global versions used for simple testing) -->\r\n    <script src="https://cdn.jsdelivr.net/npm/three@0.160.0/build/three.min.js"></script>\r\n    <script src="https://cdn.jsdelivr.net/npm/three@0.160.0/examples/jsm/loaders/GLTFLoader.js" type="module"></script>\r\n    \r\n    <!-- We need to expose GLTFLoader to window for our script to pick it up if not bundled -->\r\n    <script type="module">\r\n        import { GLTFLoader } from \'https://cdn.jsdelivr.net/npm/three@0.160.0/examples/jsm/loaders/GLTFLoader.js\';\r\n        window.GLTFLoader = GLTFLoader;\r\n    </script>\r\n\r\n\r\n\r\n<script src="https://cdn.jsdelivr.net/npm/animotion-saply-plus@5.0.8/dist/animotion-saply.min.js"></script>'
            }
          />

          <div
            data-plasmic-name={"nav"}
            data-plasmic-override={overrides.nav}
            className={classNames(projectcss.all, sty.nav)}
            data-anim={"true"}
            data-anim-props={``}
            data-anim-type={"fromTo"}
          >
            <NavigationBar
              data-plasmic-name={"navBar"}
              data-plasmic-override={overrides.navBar}
              brand={
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    sty.link__vPhok
                  )}
                  component={Link}
                  href={"#"}
                  legacyBehavior={false}
                  platform={"nextjs"}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img___5IjnY)}
                    displayHeight={"74px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={
                      hasVariant(globalVariants, "screen", "mobile")
                        ? "100%"
                        : "156px"
                    }
                    src={{
                      src: "/plasmic/tosin_umoren/images/image.png",
                      fullWidth: 313,
                      fullHeight: 149,
                      aspectRatio: undefined
                    }}
                  />
                </PlasmicLink__>
              }
              className={classNames("__wab_instance", sty.navBar)}
              closeButton={
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img___2RlFy)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  src={"https://static1.plasmic.app/close.svg"}
                />
              }
              itemsGap={8}
              menuItems={
                <React.Fragment>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__rxYe
                    )}
                    component={Link}
                    href={"/"}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"Home"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__ulMh
                    )}
                    component={Link}
                    href={`/about-us`}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"About us"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__uovFj
                    )}
                    component={Link}
                    href={"#Wdo"}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"What We Do"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__gmDJb
                    )}
                    component={Link}
                    href={`/gallery`}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"Media"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__pdZgc
                    )}
                    component={Link}
                    href={`/contact-us`}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"Contact"}
                  </PlasmicLink__>
                </React.Fragment>
              }
              openButton={
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__iDil)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  height={
                    hasVariant(globalVariants, "screen", "tablet")
                      ? "50%"
                      : undefined
                  }
                  src={"https://static1.plasmic.app/menu.svg"}
                  width={
                    hasVariant(globalVariants, "screen", "tablet")
                      ? "50%"
                      : undefined
                  }
                />
              }
              responsiveBreakpoint={768}
            />

            <PlasmicLink__
              data-plasmic-name={"heroBtn3"}
              data-plasmic-override={overrides.heroBtn3}
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.__wab_text,
                sty.heroBtn3
              )}
              component={Link}
              href={`/donation`}
              legacyBehavior={false}
              platform={"nextjs"}
            >
              {"Donate"}
            </PlasmicLink__>
          </div>
          <div
            data-plasmic-name={"hero"}
            data-plasmic-override={overrides.hero}
            className={classNames(projectcss.all, sty.hero)}
          >
            <div
              data-plasmic-name={"contents"}
              data-plasmic-override={overrides.contents}
              className={classNames(projectcss.all, sty.contents)}
            >
              <h1
                data-plasmic-name={"heroHeading"}
                data-plasmic-override={overrides.heroHeading}
                className={classNames(
                  projectcss.all,
                  projectcss.h1,
                  projectcss.__wab_text,
                  sty.heroHeading
                )}
                data-anim={"true"}
                data-anim-props={
                  '{\n\n           "from": {"autoAlpha":0,\n"x": 100},\n\n           "to": {"autoAlpha":1,\n"x": 0},\n\n           "duration": 0.8\n\n         }'
                }
                data-anim-type={"fromTo"}
              >
                {"Love, care & support for the young and old."}
              </h1>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__s3L3Q
                )}
                data-anim={"true"}
                data-anim-props={
                  '{\n\n           "from": {"autoAlpha":0,\n"scale": 0.5},\n\n           "to": {"autoAlpha":1,\n"scale": 1},\n\n           "duration": 0.8\n\n         }'
                }
                data-anim-type={"fromTo"}
              >
                {
                  "We offer educational support, skills empowerment programs, community outreach initiatives, mentorship, and humanitarian assistance designed to uplift, inspire, and create lasting impact."
                }
              </div>
              <div
                className={classNames(projectcss.all, sty.freeBox__eQyN)}
                data-gsap={"true"}
                data-gsap-props={`{

           "from": {"autoAlpha":0,
"x": -100},

           "to": {"autoAlpha":1,
"x": 0},

           "duration": 0.8

         }`}
                data-gsap-type={"fromTo"}
              >
                <PlasmicLink__
                  data-plasmic-name={"videoLink"}
                  data-plasmic-override={overrides.videoLink}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    sty.videoLink
                  )}
                  component={Link}
                  legacyBehavior={false}
                  platform={"nextjs"}
                >
                  <Icon3Icon
                    data-plasmic-name={"svg"}
                    data-plasmic-override={overrides.svg}
                    className={classNames(projectcss.all, sty.svg)}
                    role={"img"}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__kMuep
                    )}
                  >
                    {"Play Video"}
                  </div>
                </PlasmicLink__>
                <PlasmicLink__
                  data-plasmic-name={"heroBtn5"}
                  data-plasmic-override={overrides.heroBtn5}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.heroBtn5
                  )}
                  component={Link}
                  href={`/donation`}
                  legacyBehavior={false}
                  platform={"nextjs"}
                >
                  {"What we Do"}
                </PlasmicLink__>
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.column__wit0P)}>
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__qzGLw)}
                data-anim={"true"}
                data-anim-props={
                  '{\n\n           "from": {"autoAlpha":0,\n"scale": 0.5},\n\n           "to": {"autoAlpha":1,\n"scale": 1},\n\n           "duration": 0.8\n\n         }'
                }
                data-anim-type={"fromTo"}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/tosin_umoren/images/image4.png",
                  fullWidth: 1472,
                  fullHeight: 1428,
                  aspectRatio: undefined
                }}
              />
            </div>
          </div>
          <section
            data-plasmic-name={"pageWrapper"}
            data-plasmic-override={overrides.pageWrapper}
            className={classNames(
              projectcss.all,
              sty.pageWrapper,
              "intro-scroll"
            )}
          >
            <div
              data-plasmic-name={"aboutUs"}
              data-plasmic-override={overrides.aboutUs}
              className={classNames(projectcss.all, sty.aboutUs)}
              data-anim={"true"}
              data-anim-props={
                '{\n\n"scrollTrigger": {\n\n"trigger": ".intro-scroll",\n\n"start": "top 80%",\n\n"end": "bottom 20%",\n\n"scrub": true,\n\n"toggleActions": "play none none reverse"\n\n},\n\n"y": -100,\n\n"opacity": 0,\n\n"duration": 1.5,\n\n"stagger": 0.5,\n\n"ease": "power4.out"\n\n}'
              }
              data-anim-type={"from"}
            >
              <div
                data-plasmic-name={"contentsAbout"}
                data-plasmic-override={overrides.contentsAbout}
                className={classNames(projectcss.all, sty.contentsAbout)}
                data-gsap={"true"}
                data-gsap-props={``}
                data-gsap-type={"from"}
              >
                <div className={classNames(projectcss.all, sty.freeBox__tawLx)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__yq4Tg)}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__lTu2Y
                    )}
                  >
                    {"KNOW ABOUT US"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"innerContents"}
                  data-plasmic-override={overrides.innerContents}
                  className={classNames(projectcss.all, sty.innerContents)}
                >
                  <h1
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1___61NlP
                    )}
                  >
                    {"Know About us"}
                  </h1>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__qpwQ7
                    )}
                  >
                    {
                      "Tosin Umoren Foundation is a purpose-driven nonprofit organization committed to restoring dignity, hope, and opportunity to underserved children and elderly individuals across the world.\n\nThrough food support, educational assistance, and healthcare interventions, we serve vulnerable communities and help individuals rise beyond the limitations of their environment. \n\nWe currently carry out outreaches in Lagos, Oyo, Osun, and Ekiti States, impacting lives one community at a time."
                    }
                  </div>
                  <PlasmicLink__
                    data-plasmic-name={"heroBtn6"}
                    data-plasmic-override={overrides.heroBtn6}
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.heroBtn6
                    )}
                    component={Link}
                    href={`/donation`}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"Learn More"}
                  </PlasmicLink__>
                </div>
              </div>
              <div
                data-plasmic-name={"imageAbout"}
                data-plasmic-override={overrides.imageAbout}
                className={classNames(projectcss.all, sty.imageAbout)}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img___9P2Az)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={
                    hasVariant(globalVariants, "screen", "tablet")
                      ? "100%"
                      : "80%"
                  }
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/tosin_umoren/images/image5.png",
                    fullWidth: 960,
                    fullHeight: 1157,
                    aspectRatio: undefined
                  }}
                />
              </div>
            </div>
          </section>
          <div
            data-plasmic-name={"logoBanner"}
            data-plasmic-override={overrides.logoBanner}
            className={classNames(projectcss.all, sty.logoBanner)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__zf2I3)}>
              <div className={classNames(projectcss.all, sty.freeBox__w4YUl)} />
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__bvobe
                )}
              >
                {"OUR SUPPORTERS"}
              </div>
            </div>
            <div
              data-plasmic-name={"innerWrapper2"}
              data-plasmic-override={overrides.innerWrapper2}
              className={classNames(projectcss.all, sty.innerWrapper2)}
              data-anim={"true"}
              data-anim-props={
                '\n{"xPercent": -80,\n"yoyo": true,\n"duration": 15,\n"repeat": -1,\n"ease": "none"\n\n}'
              }
              data-anim-type={"to"}
            >
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__h06My)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={
                  hasVariant(globalVariants, "screen", "mobile") ? "20%" : "15%"
                }
                loading={"lazy"}
                src={{
                  src: "/plasmic/tosin_umoren/images/image6.png",
                  fullWidth: 285,
                  fullHeight: 56,
                  aspectRatio: undefined
                }}
              />

              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__nNeiD)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={
                  hasVariant(globalVariants, "screen", "mobile") ? "20%" : "15%"
                }
                loading={"lazy"}
                src={{
                  src: "/plasmic/tosin_umoren/images/image34.png",
                  fullWidth: 274,
                  fullHeight: 62,
                  aspectRatio: undefined
                }}
              />

              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__q5BK)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={
                  hasVariant(globalVariants, "screen", "mobile") ? "20%" : "15%"
                }
                loading={"lazy"}
                src={{
                  src: "/plasmic/tosin_umoren/images/image35.png",
                  fullWidth: 251,
                  fullHeight: 57,
                  aspectRatio: undefined
                }}
              />

              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__rDr9M)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={
                  hasVariant(globalVariants, "screen", "mobile") ? "20%" : "15%"
                }
                loading={"lazy"}
                src={{
                  src: "/plasmic/tosin_umoren/images/image36.png",
                  fullWidth: 247,
                  fullHeight: 50,
                  aspectRatio: undefined
                }}
              />

              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__qcxPu)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={
                  hasVariant(globalVariants, "screen", "mobile") ? "20%" : "15%"
                }
                loading={"lazy"}
                src={{
                  src: "/plasmic/tosin_umoren/images/image37.png",
                  fullWidth: 268,
                  fullHeight: 63,
                  aspectRatio: undefined
                }}
              />

              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__zzDdY)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={
                  hasVariant(globalVariants, "screen", "mobile") ? "20%" : "15%"
                }
                loading={"lazy"}
                src={{
                  src: "/plasmic/tosin_umoren/images/image6.png",
                  fullWidth: 285,
                  fullHeight: 56,
                  aspectRatio: undefined
                }}
              />

              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__zjZtd)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={
                  hasVariant(globalVariants, "screen", "mobile") ? "20%" : "15%"
                }
                loading={"lazy"}
                src={{
                  src: "/plasmic/tosin_umoren/images/image34.png",
                  fullWidth: 274,
                  fullHeight: 62,
                  aspectRatio: undefined
                }}
              />

              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__m1POh)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={
                  hasVariant(globalVariants, "screen", "mobile") ? "20%" : "15%"
                }
                loading={"lazy"}
                src={{
                  src: "/plasmic/tosin_umoren/images/image6.png",
                  fullWidth: 285,
                  fullHeight: 56,
                  aspectRatio: undefined
                }}
              />

              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__kNVk)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={
                  hasVariant(globalVariants, "screen", "mobile") ? "20%" : "15%"
                }
                loading={"lazy"}
                src={{
                  src: "/plasmic/tosin_umoren/images/image6.png",
                  fullWidth: 285,
                  fullHeight: 56,
                  aspectRatio: undefined
                }}
              />

              <PlasmicImg__
                alt={""}
                className={classNames(sty.img___1BgTv)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={
                  hasVariant(globalVariants, "screen", "mobile") ? "20%" : "15%"
                }
                loading={"lazy"}
                src={{
                  src: "/plasmic/tosin_umoren/images/image6.png",
                  fullWidth: 285,
                  fullHeight: 56,
                  aspectRatio: undefined
                }}
              />
            </div>
          </div>
          <section
            data-plasmic-name={"whatWeDo2"}
            data-plasmic-override={overrides.whatWeDo2}
            className={classNames(projectcss.all, sty.whatWeDo2, "mid-scroll")}
            id={"Wdo"}
          >
            <div
              data-plasmic-name={"whatWeDo"}
              data-plasmic-override={overrides.whatWeDo}
              className={classNames(projectcss.all, sty.whatWeDo)}
              data-anim={"true"}
              data-anim-props={
                hasVariant(globalVariants, "screen", "tablet")
                  ? ``
                  : '{\n\n"scrollTrigger": {\n\n"trigger": ".mid-scroll",\n\n"start": "top 80%",\n\n"end": "bottom 20%",\n\n"scrub": true,\n\n"toggleActions": "play none none reverse"\n\n},\n\n"y": -100,\n\n"opacity": 0,\n\n"duration": 1.5,\n\n"stagger": 0.5,\n\n"ease": "power4.out"\n\n}'
              }
              data-anim-type={"from"}
            >
              <div
                data-plasmic-name={"contentsAbout2"}
                data-plasmic-override={overrides.contentsAbout2}
                className={classNames(projectcss.all, sty.contentsAbout2)}
              >
                <div
                  className={classNames(projectcss.all, sty.freeBox___7PGyd)}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox__oWVw5)}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___51Xj9
                    )}
                  >
                    {"WHAT WE DO"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"innerContents2"}
                  data-plasmic-override={overrides.innerContents2}
                  className={classNames(
                    projectcss.all,
                    sty.innerContents2,
                    "object-scroll"
                  )}
                >
                  <h1
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1__tcyu
                    )}
                  >
                    {"Some Services We \nProvide For People "}
                  </h1>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__zZ9VF
                    )}
                  >
                    {
                      "We offer educational support, community outreach initiatives, mentorship, and humanitarian assistance designed to uplift, inspire, and create lasting impact."
                    }
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__a5SwJ)}
                    data-anim={"true"}
                    data-anim-props={
                      hasVariant(globalVariants, "screen", "tablet")
                        ? ``
                        : '{\n\n"scrollTrigger": {\n\n"trigger": ".object-scroll",\n\n"start": "top 80%",\n\n"end": "bottom 20%",\n\n"scrub": true,\n\n"toggleActions": "play none none reverse"\n\n},\n\n"y": -100,\n\n"opacity": 0,\n\n"duration": 2,\n\n"stagger": 1.5,\n\n"ease": "power4.out"\n\n}'
                    }
                    data-anim-type={"from"}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__yei3F)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__ussea
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__wjdV7
                          )}
                        >
                          {"Food & Welfare Outreach"}
                        </div>
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__j8Ob7)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"5%"}
                          loading={"lazy"}
                          src={{
                            src: "/plasmic/tosin_umoren/images/image8.png",
                            fullWidth: 56,
                            fullHeight: 56,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__gKxfe
                        )}
                      >
                        {
                          "Distribution of food items, money and essential supplies to vulnerable families and elderly individuals."
                        }
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__ow3AV)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__f5N3N
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__h69BG
                          )}
                        >
                          {"Healthcare Assistance"}
                        </div>
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__o2EVk)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"5%"}
                          loading={"lazy"}
                          src={{
                            src: "/plasmic/tosin_umoren/images/image9.png",
                            fullWidth: 56,
                            fullHeight: 56,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__yS6L
                        )}
                      >
                        {
                          "Payment of hospital bills and medical assistance for those who cannot afford treatment."
                        }
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__tQPjc)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__x9PH
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__hcQU
                          )}
                        >
                          {"Education Support"}
                        </div>
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__w6AtS)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"5%"}
                          loading={"lazy"}
                          src={{
                            src: "/plasmic/tosin_umoren/images/image10.png",
                            fullWidth: 56,
                            fullHeight: 56,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__kqjsf
                        )}
                      >
                        {
                          "Providing school fees assistance, learning materials, and encouragement to undeserved children."
                        }
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__ue1M2)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___1CAeH
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__sHaZa
                          )}
                        >
                          {"Mindset & Parental Reorientation"}
                        </div>
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img___7B1Mu)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"5%"}
                          loading={"lazy"}
                          src={{
                            src: "/plasmic/tosin_umoren/images/image11.png",
                            fullWidth: 56,
                            fullHeight: 55,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__wqNCd
                        )}
                      >
                        {
                          "Programs focused on reshaping limiting beliefs and helping parents raise emotionally healthy children."
                        }
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div
                data-plasmic-name={"imageAbout2"}
                data-plasmic-override={overrides.imageAbout2}
                className={classNames(projectcss.all, sty.imageAbout2)}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__twTTj)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={
                    hasVariant(globalVariants, "screen", "tablet")
                      ? "100%"
                      : "80%"
                  }
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/tosin_umoren/images/image7.png",
                    fullWidth: 720,
                    fullHeight: 987,
                    aspectRatio: undefined
                  }}
                />
              </div>
            </div>
          </section>
          <section
            data-plasmic-name={"pageWrapper2"}
            data-plasmic-override={overrides.pageWrapper2}
            className={classNames(
              projectcss.all,
              sty.pageWrapper2,
              "after-scroll"
            )}
          >
            <div
              data-plasmic-name={"aboutUs2"}
              data-plasmic-override={overrides.aboutUs2}
              className={classNames(projectcss.all, sty.aboutUs2)}
            >
              <div
                data-plasmic-name={"contentsAbout3"}
                data-plasmic-override={overrides.contentsAbout3}
                className={classNames(projectcss.all, sty.contentsAbout3)}
                data-anim={"true"}
                data-anim-props={
                  '{\n\n"scrollTrigger": {\n\n"trigger": ".after-scroll",\n\n"start": "top 80%",\n\n"end": "bottom 20%",\n\n"scrub": true,\n\n"toggleActions": "play none none reverse"\n\n},\n\n"x": -100,\n\n"opacity": 0,\n\n"duration": 1.5,\n\n"stagger": 0.5,\n\n"ease": "power4.out"\n\n}'
                }
                data-anim-type={"from"}
              >
                <div className={classNames(projectcss.all, sty.freeBox__fs4SY)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox___7K3Oe)}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__x0H80
                    )}
                  >
                    {"Projects we have done"}
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__tcMhG)}>
                  <h1
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1___0G7CZ
                    )}
                  >
                    {"IMPACT & STORIES"}
                  </h1>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ykqAu
                    )}
                  >
                    {"What We\u2019ve Done So Far"}
                  </div>
                </div>
              </div>
            </div>
            <div
              className={classNames(projectcss.all, sty.columns__zrBv)}
              data-anim={"true"}
              data-anim-props={
                hasVariant(globalVariants, "screen", "tablet")
                  ? ``
                  : '{\n\n"scrollTrigger": {\n\n"trigger": ".after-scroll",\n\n"start": "top 80%",\n\n"end": "bottom 20%",\n\n"scrub": true,\n\n"toggleActions": "play none none reverse"\n\n},\n\n"y": -100,\n\n"opacity": 0,\n\n"duration": 1.5,\n\n"stagger": 0.5,\n\n"ease": "power4.out"\n\n}'
              }
              data-anim-type={"from"}
            >
              <div className={classNames(projectcss.all, sty.column__yRsgv)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__xiuiR
                  )}
                >
                  {"Distributed Food Items to Rural Elderly Individuals"}
                </div>
                <PlasmicLink__
                  data-plasmic-name={"videoLink2"}
                  data-plasmic-override={overrides.videoLink2}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    sty.videoLink2
                  )}
                  component={Link}
                  legacyBehavior={false}
                  platform={"nextjs"}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___4MgQi
                    )}
                  >
                    {"Learn More"}
                  </div>
                </PlasmicLink__>
              </div>
              <div className={classNames(projectcss.all, sty.column___6B54W)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__wrefq
                  )}
                >
                  {"Paid Hospital Bills For Vulnerable Individuals"}
                </div>
                <PlasmicLink__
                  data-plasmic-name={"videoLink3"}
                  data-plasmic-override={overrides.videoLink3}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    sty.videoLink3
                  )}
                  component={Link}
                  legacyBehavior={false}
                  platform={"nextjs"}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__wi3CJ
                    )}
                  >
                    {"Learn More"}
                  </div>
                </PlasmicLink__>
              </div>
              <div className={classNames(projectcss.all, sty.column__jg6Vl)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___8ZyyH
                  )}
                >
                  {"Supported Children With Education Materials"}
                </div>
                <PlasmicLink__
                  data-plasmic-name={"videoLink4"}
                  data-plasmic-override={overrides.videoLink4}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    sty.videoLink4
                  )}
                  component={Link}
                  legacyBehavior={false}
                  platform={"nextjs"}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___94LeG
                    )}
                  >
                    {"Learn More"}
                  </div>
                </PlasmicLink__>
              </div>
              <div className={classNames(projectcss.all, sty.column__j7A0T)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__phX5C
                  )}
                >
                  {"Active Monthly Outreaches "}
                </div>
                <PlasmicLink__
                  data-plasmic-name={"videoLink5"}
                  data-plasmic-override={overrides.videoLink5}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    sty.videoLink5
                  )}
                  component={Link}
                  legacyBehavior={false}
                  platform={"nextjs"}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__lbe8H
                    )}
                  >
                    {"Learn More"}
                  </div>
                </PlasmicLink__>
              </div>
            </div>
          </section>
          <section
            data-plasmic-name={"joinCOmmunity"}
            data-plasmic-override={overrides.joinCOmmunity}
            className={classNames(
              projectcss.all,
              sty.joinCOmmunity,
              "C-scroll"
            )}
          >
            <div
              data-plasmic-name={"community"}
              data-plasmic-override={overrides.community}
              className={classNames(projectcss.all, sty.community)}
              data-anim={"true"}
              data-anim-props={
                hasVariant(globalVariants, "screen", "tablet")
                  ? ``
                  : '{\n\n"scrollTrigger": {\n\n"trigger": ".C-scroll",\n\n"start": "top 80%",\n\n"end": "bottom 20%",\n\n"scrub": true,\n\n"toggleActions": "play none none reverse"\n\n},\n\n"y": -100,\n\n"opacity": 0,\n\n"duration": 1.5,\n\n"stagger": 0.5,\n\n"ease": "power4.out"\n\n}'
              }
              data-anim-type={"from"}
            >
              <div
                data-plasmic-name={"contentsAbout4"}
                data-plasmic-override={overrides.contentsAbout4}
                className={classNames(projectcss.all, sty.contentsAbout4)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__jiQep)}>
                  <h1
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1__px90
                    )}
                  >
                    {"Join Our Community "}
                  </h1>
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__urixt
                  )}
                >
                  {
                    "Join our community and be part of a movement that creates hope, change, and lasting impact."
                  }
                </div>
                <PlasmicLink__
                  data-plasmic-name={"heroBtn7"}
                  data-plasmic-override={overrides.heroBtn7}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.heroBtn7
                  )}
                  component={Link}
                  href={`/community`}
                  legacyBehavior={false}
                  platform={"nextjs"}
                >
                  {"Join Community"}
                </PlasmicLink__>
              </div>
              <div
                data-plasmic-name={"contentsAbout5"}
                data-plasmic-override={overrides.contentsAbout5}
                className={classNames(projectcss.all, sty.contentsAbout5)}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__c2Zw)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"75%"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/tosin_umoren/images/image22.png",
                    fullWidth: 1156,
                    fullHeight: 1534,
                    aspectRatio: undefined
                  }}
                />
              </div>
            </div>
          </section>
          <div
            data-plasmic-name={"events"}
            data-plasmic-override={overrides.events}
            className={classNames(projectcss.all, sty.events, "E-scroll")}
          >
            <div
              className={classNames(projectcss.all, sty.freeBox__a62Is)}
              data-anim={"true"}
              data-anim-props={
                '{\n\n"scrollTrigger": {\n\n"trigger": ".E-scroll",\n\n"start": "top 80%",\n\n"end": "bottom 20%",\n\n"scrub": true,\n\n"toggleActions": "play none none reverse"\n\n},\n\n"x": -100,\n\n"opacity": 0,\n\n"duration": 1.5,\n\n"stagger": 0.5,\n\n"ease": "power4.out"\n\n}'
              }
              data-anim-type={"from"}
            >
              <div className={classNames(projectcss.all, sty.freeBox__nmOo6)} />
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__vLosL
                )}
              >
                {"Our Events"}
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__zJgX1)}>
              <div
                className={classNames(projectcss.all, sty.columns__uryLs)}
                data-anim={"true"}
                data-anim-props={
                  hasVariant(globalVariants, "screen", "tablet")
                    ? ``
                    : '{\n\n"scrollTrigger": {\n\n"trigger": ".E-scroll",\n\n"start": "top 80%",\n\n"end": "bottom 20%",\n\n"scrub": true,\n\n"toggleActions": "play none none reverse"\n\n},\n\n"y": -100,\n\n"opacity": 0,\n\n"duration": 1.5,\n\n"stagger": 0.5,\n\n"ease": "power4.out"\n\n}'
                }
                data-anim-type={"from"}
              >
                <div className={classNames(projectcss.all, sty.column__x3Iok)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__jhIs0)}
                  >
                    <h1
                      className={classNames(
                        projectcss.all,
                        projectcss.h1,
                        projectcss.__wab_text,
                        sty.h1__wpgVw
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{"7TH\n"}</React.Fragment>
                        {
                          <h4
                            className={classNames(
                              projectcss.all,
                              projectcss.h4,
                              projectcss.__wab_text,
                              sty.h4__jUvbl
                            )}
                          >
                            <React.Fragment>
                              <span
                                className={
                                  "plasmic_default__all plasmic_default__span"
                                }
                                style={{ fontWeight: 700 }}
                              >
                                {"MARCH"}
                              </span>
                            </React.Fragment>
                          </h4>
                        }
                        <React.Fragment>{""}</React.Fragment>
                      </React.Fragment>
                    </h1>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__lIyow)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__paGgi
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__zfmmW
                          )}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___02THw
                          )}
                        >
                          {"Next Events"}
                        </div>
                      </div>
                      <h1
                        className={classNames(
                          projectcss.all,
                          projectcss.h1,
                          projectcss.__wab_text,
                          sty.h1__qC8IO
                        )}
                      >
                        {"Celebration of Mothers for Women\u2019s Day"}
                      </h1>
                    </div>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__iaTl
                      )}
                      component={Link}
                      legacyBehavior={false}
                      platform={"nextjs"}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__gikuc)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={
                          hasVariant(globalVariants, "screen", "mobile")
                            ? "60%"
                            : "80%"
                        }
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/tosin_umoren/images/image23.png",
                          fullWidth: 112,
                          fullHeight: 112,
                          aspectRatio: undefined
                        }}
                      />
                    </PlasmicLink__>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.column__krLah)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__sl2W)}
                  >
                    <h1
                      className={classNames(
                        projectcss.all,
                        projectcss.h1,
                        projectcss.__wab_text,
                        sty.h1__wDbqd
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{"27TH\n"}</React.Fragment>
                        {
                          <h4
                            className={classNames(
                              projectcss.all,
                              projectcss.h4,
                              projectcss.__wab_text,
                              sty.h4__d2Ud6
                            )}
                          >
                            <React.Fragment>
                              <span
                                className={
                                  "plasmic_default__all plasmic_default__span"
                                }
                                style={{ fontWeight: 700 }}
                              >
                                {"MAY"}
                              </span>
                            </React.Fragment>
                          </h4>
                        }
                        <React.Fragment>{""}</React.Fragment>
                      </React.Fragment>
                    </h1>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__fTdle)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__sljEe
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__j1Dv6
                          )}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___3ShRy
                          )}
                        >
                          {"Next Events"}
                        </div>
                      </div>
                      <h1
                        className={classNames(
                          projectcss.all,
                          projectcss.h1,
                          projectcss.__wab_text,
                          sty.h1__xr0Ac
                        )}
                      >
                        {
                          "Children\u2019s Day celebration in collaboration with a media company."
                        }
                      </h1>
                    </div>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__f9OUm
                      )}
                      component={Link}
                      legacyBehavior={false}
                      platform={"nextjs"}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img___9ZYuQ)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={
                          hasVariant(globalVariants, "screen", "mobile")
                            ? "60%"
                            : "80%"
                        }
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/tosin_umoren/images/image23.png",
                          fullWidth: 112,
                          fullHeight: 112,
                          aspectRatio: undefined
                        }}
                      />
                    </PlasmicLink__>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames(projectcss.all, sty.footer, "F-scroll")}
          >
            <div
              className={classNames(projectcss.all, sty.columns__kML)}
              data-anim={"true"}
              data-anim-props={
                hasVariant(globalVariants, "screen", "tablet")
                  ? ``
                  : '{\n\n"scrollTrigger": {\n\n"trigger": ".F-scroll",\n\n"start": "top 80%",\n\n"end": "bottom 20%",\n\n"scrub": true,\n\n"toggleActions": "play none none reverse"\n\n},\n\n"y": -100,\n\n"opacity": 0,\n\n"duration": 1.5,\n\n"stagger": 0.5,\n\n"ease": "power4.out"\n\n}'
              }
              data-anim-type={"from"}
            >
              <div className={classNames(projectcss.all, sty.column__p6DM9)}>
                <div className={classNames(projectcss.all, sty.freeBox__bFGiM)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img___3KO)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/tosin_umoren/images/image.png",
                      fullWidth: 313,
                      fullHeight: 149,
                      aspectRatio: undefined
                    }}
                  />
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__h7Wq4)}>
                <h1
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.__wab_text,
                    sty.h1___6JQd
                  )}
                >
                  {"Contact Us"}
                </h1>
                <div className={classNames(projectcss.all, sty.freeBox__wEg51)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__vJppx
                    )}
                  >
                    {"EMAIL US:"}
                  </div>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__o69Q2
                    )}
                    component={Link}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"tosinumorenfoundation@gmail.com\r"}
                  </PlasmicLink__>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__ms1Jr)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__doWrc
                    )}
                  >
                    {"PHONE:"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__jsgqh
                    )}
                  >
                    {"+234 813 072 2129, +1760 829 0816"}
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__eSbo)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__qOhVw
                    )}
                  >
                    {"LOCATION:"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__mOyQc
                    )}
                  >
                    {"Nigeria (Outreaches across Lagos, Oyo, Osun & Ekiti)"}
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__fS)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ooQ3
                    )}
                  >
                    {"SOCIALS:"}
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__uTgm7)}
                  >
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__iCz7P
                      )}
                      component={Link}
                      legacyBehavior={false}
                      platform={"nextjs"}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__lAk2)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={
                          hasVariant(globalVariants, "screen", "mobile")
                            ? "80%"
                            : "auto"
                        }
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/tosin_umoren/images/image26.png",
                          fullWidth: 36,
                          fullHeight: 36,
                          aspectRatio: undefined
                        }}
                      />
                    </PlasmicLink__>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link___7Cqgy
                      )}
                      component={Link}
                      legacyBehavior={false}
                      platform={"nextjs"}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__jcxee)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={
                          hasVariant(globalVariants, "screen", "mobile")
                            ? "80%"
                            : "auto"
                        }
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/tosin_umoren/images/image25.png",
                          fullWidth: 36,
                          fullHeight: 36,
                          aspectRatio: undefined
                        }}
                      />
                    </PlasmicLink__>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__uobL
                      )}
                      component={Link}
                      legacyBehavior={false}
                      platform={"nextjs"}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__qs7Hs)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={
                          hasVariant(globalVariants, "screen", "mobile")
                            ? "80%"
                            : "auto"
                        }
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/tosin_umoren/images/image24.png",
                          fullWidth: 36,
                          fullHeight: 36,
                          aspectRatio: undefined
                        }}
                      />
                    </PlasmicLink__>
                  </div>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__jPkEt)}>
                <h1
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.__wab_text,
                    sty.h1__ap6A4
                  )}
                >
                  {"Links"}
                </h1>
                <div
                  className={classNames(projectcss.all, sty.freeBox___03UVr)}
                >
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__lxLac
                    )}
                    component={Link}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"Projects"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__qTuof
                    )}
                    component={Link}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"Events"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__nl7F0
                    )}
                    component={Link}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"Donate"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link___0V57B
                    )}
                    component={Link}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"News"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__frnWx
                    )}
                    component={Link}
                    href={`/gallery`}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {"Gallery"}
                  </PlasmicLink__>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__u4Kbr)}>
                <h1
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.__wab_text,
                    sty.h1__jkXo9
                  )}
                >
                  {"Subscribe to get latest updates"}
                </h1>
                {(() => {
                  const child$Props = {
                    className: classNames("__wab_instance", sty.form),
                    extendedOnValuesChange: async (...eventArgs) => {
                      generateStateOnChangePropForCodeComponents(
                        $state,
                        "value",
                        ["form", "value"],
                        FormWrapper_Helpers
                      ).apply(null, eventArgs);
                    },
                    formItems: [
                      { label: "Name", name: "name", inputType: "Text" },
                      {
                        label: "Message",
                        name: "message",
                        inputType: "Text Area"
                      }
                    ],

                    labelCol: { span: 8, horizontalOnly: true },
                    layout: "vertical",
                    mode: "advanced",
                    onIsSubmittingChange: async (...eventArgs) => {
                      generateStateOnChangePropForCodeComponents(
                        $state,
                        "isSubmitting",
                        ["form", "isSubmitting"],
                        FormWrapper_Helpers
                      ).apply(null, eventArgs);
                    },
                    ref: ref => {
                      $refs["form"] = ref;
                    },
                    submitSlot: null,
                    wrapperCol: { span: 16, horizontalOnly: true }
                  };
                  initializeCodeComponentStates(
                    $state,
                    [
                      {
                        name: "value",
                        plasmicStateName: "form.value"
                      },
                      {
                        name: "isSubmitting",
                        plasmicStateName: "form.isSubmitting"
                      }
                    ],

                    [],
                    FormWrapper_Helpers ?? {},
                    child$Props
                  );
                  return (
                    <FormWrapper
                      data-plasmic-name={"form"}
                      data-plasmic-override={overrides.form}
                      {...child$Props}
                    >
                      <FormItemWrapper
                        data-plasmic-name={"formField"}
                        data-plasmic-override={overrides.formField}
                        className={classNames("__wab_instance", sty.formField)}
                        label={
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__yXmHj
                            )}
                          >
                            {"Your Email"}
                          </div>
                        }
                        name={"email"}
                      >
                        {(() => {
                          const child$Props = {
                            className: classNames("__wab_instance", sty.input),
                            onChange: async (...eventArgs) => {
                              generateStateOnChangePropForCodeComponents(
                                $state,
                                "value",
                                ["input", "value"],
                                AntdInput_Helpers
                              ).apply(null, eventArgs);
                            },
                            placeholder: "Your Email",
                            size: "large",
                            type: "email",
                            value: generateStateValueProp($state, [
                              "input",
                              "value"
                            ])
                          };
                          initializeCodeComponentStates(
                            $state,
                            [
                              {
                                name: "value",
                                plasmicStateName: "input.value"
                              }
                            ],

                            [],
                            AntdInput_Helpers ?? {},
                            child$Props
                          );
                          return (
                            <AntdInput
                              data-plasmic-name={"input"}
                              data-plasmic-override={overrides.input}
                              {...child$Props}
                            />
                          );
                        })()}
                      </FormItemWrapper>
                      <AntdButton
                        data-plasmic-name={"button"}
                        data-plasmic-override={overrides.button}
                        className={classNames("__wab_instance", sty.button)}
                        submitsForm={true}
                        type={"primary"}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__dG1F7
                          )}
                        >
                          {"Subscribe"}
                        </div>
                      </AntdButton>
                    </FormWrapper>
                  );
                })()}
              </div>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  homepage: [
    "homepage",
    "embedHtml",
    "nav",
    "navBar",
    "heroBtn3",
    "hero",
    "contents",
    "heroHeading",
    "videoLink",
    "svg",
    "heroBtn5",
    "pageWrapper",
    "aboutUs",
    "contentsAbout",
    "innerContents",
    "heroBtn6",
    "imageAbout",
    "logoBanner",
    "innerWrapper2",
    "whatWeDo2",
    "whatWeDo",
    "contentsAbout2",
    "innerContents2",
    "imageAbout2",
    "pageWrapper2",
    "aboutUs2",
    "contentsAbout3",
    "videoLink2",
    "videoLink3",
    "videoLink4",
    "videoLink5",
    "joinCOmmunity",
    "community",
    "contentsAbout4",
    "heroBtn7",
    "contentsAbout5",
    "events",
    "footer",
    "form",
    "formField",
    "input",
    "button"
  ],

  embedHtml: ["embedHtml"],
  nav: ["nav", "navBar", "heroBtn3"],
  navBar: ["navBar"],
  heroBtn3: ["heroBtn3"],
  hero: ["hero", "contents", "heroHeading", "videoLink", "svg", "heroBtn5"],
  contents: ["contents", "heroHeading", "videoLink", "svg", "heroBtn5"],
  heroHeading: ["heroHeading"],
  videoLink: ["videoLink", "svg"],
  svg: ["svg"],
  heroBtn5: ["heroBtn5"],
  pageWrapper: [
    "pageWrapper",
    "aboutUs",
    "contentsAbout",
    "innerContents",
    "heroBtn6",
    "imageAbout"
  ],

  aboutUs: [
    "aboutUs",
    "contentsAbout",
    "innerContents",
    "heroBtn6",
    "imageAbout"
  ],

  contentsAbout: ["contentsAbout", "innerContents", "heroBtn6"],
  innerContents: ["innerContents", "heroBtn6"],
  heroBtn6: ["heroBtn6"],
  imageAbout: ["imageAbout"],
  logoBanner: ["logoBanner", "innerWrapper2"],
  innerWrapper2: ["innerWrapper2"],
  whatWeDo2: [
    "whatWeDo2",
    "whatWeDo",
    "contentsAbout2",
    "innerContents2",
    "imageAbout2"
  ],

  whatWeDo: ["whatWeDo", "contentsAbout2", "innerContents2", "imageAbout2"],
  contentsAbout2: ["contentsAbout2", "innerContents2"],
  innerContents2: ["innerContents2"],
  imageAbout2: ["imageAbout2"],
  pageWrapper2: [
    "pageWrapper2",
    "aboutUs2",
    "contentsAbout3",
    "videoLink2",
    "videoLink3",
    "videoLink4",
    "videoLink5"
  ],

  aboutUs2: ["aboutUs2", "contentsAbout3"],
  contentsAbout3: ["contentsAbout3"],
  videoLink2: ["videoLink2"],
  videoLink3: ["videoLink3"],
  videoLink4: ["videoLink4"],
  videoLink5: ["videoLink5"],
  joinCOmmunity: [
    "joinCOmmunity",
    "community",
    "contentsAbout4",
    "heroBtn7",
    "contentsAbout5"
  ],

  community: ["community", "contentsAbout4", "heroBtn7", "contentsAbout5"],
  contentsAbout4: ["contentsAbout4", "heroBtn7"],
  heroBtn7: ["heroBtn7"],
  contentsAbout5: ["contentsAbout5"],
  events: ["events"],
  footer: ["footer", "form", "formField", "input", "button"],
  form: ["form", "formField", "input", "button"],
  formField: ["formField", "input"],
  input: ["input"],
  button: ["button"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "homepage") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("homepage"),
  {
    // Helper components rendering sub-elements
    embedHtml: makeNodeComponent("embedHtml"),
    nav: makeNodeComponent("nav"),
    navBar: makeNodeComponent("navBar"),
    heroBtn3: makeNodeComponent("heroBtn3"),
    hero: makeNodeComponent("hero"),
    contents: makeNodeComponent("contents"),
    heroHeading: makeNodeComponent("heroHeading"),
    videoLink: makeNodeComponent("videoLink"),
    svg: makeNodeComponent("svg"),
    heroBtn5: makeNodeComponent("heroBtn5"),
    pageWrapper: makeNodeComponent("pageWrapper"),
    aboutUs: makeNodeComponent("aboutUs"),
    contentsAbout: makeNodeComponent("contentsAbout"),
    innerContents: makeNodeComponent("innerContents"),
    heroBtn6: makeNodeComponent("heroBtn6"),
    imageAbout: makeNodeComponent("imageAbout"),
    logoBanner: makeNodeComponent("logoBanner"),
    innerWrapper2: makeNodeComponent("innerWrapper2"),
    whatWeDo2: makeNodeComponent("whatWeDo2"),
    whatWeDo: makeNodeComponent("whatWeDo"),
    contentsAbout2: makeNodeComponent("contentsAbout2"),
    innerContents2: makeNodeComponent("innerContents2"),
    imageAbout2: makeNodeComponent("imageAbout2"),
    pageWrapper2: makeNodeComponent("pageWrapper2"),
    aboutUs2: makeNodeComponent("aboutUs2"),
    contentsAbout3: makeNodeComponent("contentsAbout3"),
    videoLink2: makeNodeComponent("videoLink2"),
    videoLink3: makeNodeComponent("videoLink3"),
    videoLink4: makeNodeComponent("videoLink4"),
    videoLink5: makeNodeComponent("videoLink5"),
    joinCOmmunity: makeNodeComponent("joinCOmmunity"),
    community: makeNodeComponent("community"),
    contentsAbout4: makeNodeComponent("contentsAbout4"),
    heroBtn7: makeNodeComponent("heroBtn7"),
    contentsAbout5: makeNodeComponent("contentsAbout5"),
    events: makeNodeComponent("events"),
    footer: makeNodeComponent("footer"),
    form: makeNodeComponent("form"),
    formField: makeNodeComponent("formField"),
    input: makeNodeComponent("input"),
    button: makeNodeComponent("button"),
    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,
    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pageRoute: "/",
      pagePath: "/",
      params: {},
      query: {}
    })
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
